discordjs/discord-api-types

common/index.ts

https://github.com/discord/discord-api-docs/pull/2043

chore: add error code 20028

---

v6/payloads/user.ts

PR: https://github.com/discord/discord-api-docs/pull/2011

chore(UserFlags): update for PR discord/discord-api-docs#2011

---

v6/payloads/guild.ts
v6/payloads/webhook.ts

PR: https://github.com/discord/discord-api-docs/pull/1886/

chore(Types): update for PR discord/discord-api-docs#1886

---

v6/payloads/gateway.ts

Ref: https://github.com/discord/discord-api-docs/commit/cd6c72a9a297c32ef59f3243eaddd9167fb4e1c3

feat(ActivityType): add Competing activity type

---

v8/rest/guild.ts

ref: https://github.com/discord/discord-api-docs/commit/de09ff2a37e117a9429fca46a5d12cd59a15dcc6

chore: remove RESTGetAPIGuildIntegrationQuery (per Discord)

---

common/index.ts
v8/payloads/channel.ts

feat(Message): Stickers

---

common/index.ts
package-lock.json
v8/payloads/guild.ts
v8/payloads/index.ts
v8/payloads/template.ts
v8/rest/guild.ts
v8/rest/index.ts
v8/rest/template.ts

https://github.com/discord/discord-api-docs/pull/1712
https://github.com/discord/discord-api-docs/pull/2144

feat: server templates

---

v8/payloads/guild.ts

ref: https://github.com/discord/discord-api-docs/pull/2345

chore: add `pending` property to GuildMember

---

common/index.ts
package-lock.json
package.json
tsconfig.json
v8/gateway/index.ts
v8/payloads/auditLog.ts
v8/payloads/channel.ts
v8/payloads/gateway.ts
v8/payloads/guild.ts
v8/payloads/index.ts
v8/payloads/interactions.ts
v8/payloads/invite.ts
v8/payloads/teams.ts
v8/payloads/user.ts
v8/payloads/webhook.ts
v8/rest/channel.ts
v8/rest/guild.ts
v8/rest/index.ts
v8/rest/interactions.ts

ref: https://github.com/discord/discord-api-docs/pull/2295
Zoomies!
<sup>Also did some other small breaking changes because why not!</sup>

chore: Slash Commands typings

---

v8/payloads/interactions.ts

https://github.com/discord/discord-api-docs/pull/2408

chore(interactions): add `permissions` property to received member

---

v8/payloads/gateway.ts

https://github.com/discord/discord-api-docs/pull/2219

feat(GatewayActivity): add missing fields

---

v8/rest/index.ts
v8/rest/oauth2.ts

https://github.com/discord/discord-api-docs/pull/2493

feat(OAuth2): add `/oauth2/@me` route

---

common/index.ts
v8/rest/webhook.ts

https://github.com/discord/discord-api-docs/pull/2461

feat(Webhook): add Edit Webhook Message result and error 50027

---

v8/gateway/index.ts

ref: https://github.com/discord/discord-api-docs/commit/762da2

feat: add Application Command events

---

common/index.ts
v8/rest/index.ts
v8/rest/interactions.ts

ref: https://github.com/discord/discord-api-docs/commit/093ea60e52e86d78ae22635abf5b64c358e6d04d

feat: add GET single Application Command

---

common/index.ts

This PR creates a common object of message formats as regexes.
https://discord.com/developers/docs/reference#message-formatting-formats

feat: implement FormatPatterns

---

v8/rest/channel.ts

https://github.com/discord/discord-api-docs/pull/2572

feat(APIMessageReferenceSend): add `fail_if_not_exists`

---

v8/payloads/auditLog.ts

ref: https://github.com/discord/discord-api-docs/pull/2570

chore: add missing audit log keys

---

v8/payloads/interactions.ts

https://github.com/discord/discord-api-docs/pull/2615

feat(APIInteractionResponse, APIInteractionResponseType): update for UI changes

---

deno/v8/payloads/channel.ts
deno/v8/payloads/interactions.ts
deno/v8/rest/guild.ts
v8/payloads/channel.ts
v8/payloads/interactions.ts

https://github.com/discord/discord-api-docs/pull/2615

feat(APIMessage): add `interaction`

---

deno/v8/payloads/interactions.ts
deno/v8/rest/guild.ts
v8/payloads/interactions.ts

chore(APIInteractionResponse, APIInteractionResponseType): remove old response types

---

package-lock.json
package.json

chore: release 0.13.1

---

package-lock.json
package.json

chore: release 0.13.2

---

.npmrc
package-lock.json
package.json

chore: fix globs

---

deno/v8/payloads/channel.ts
deno/v8/payloads/permissions.ts
deno/v8/payloads/voice.ts
deno/v8/rest/guild.ts
deno/v8/rest/mod.ts
package.json
v8/payloads/channel.ts
v8/payloads/permissions.ts
v8/payloads/voice.ts
v8/rest/guild.ts
v8/rest/index.ts

Stage channels!
https://github.com/discord/discord-api-docs/pull/2751

feat: stage channels!

---

deno/payloads/v8/interactions.ts
payloads/v8/interactions.ts

fix(APIApplicationCommand): default_permission

---

CHANGELOG.md
package-lock.json
package.json
scripts/deno.mjs
scripts/versions.mjs

chore(release): 0.15.0 🎉

---

deno/rest/common.ts
rest/common.ts

https://github.com/discord/discord-api-docs/pull/2799

feat(RESTJSONErrorCode): add `UnknownInteraction` error code

---

deno/payloads/v8/guild.ts
payloads/v8/guild.ts

https://github.com/discord/discord-api-docs/pull/2805

feat(Guild): add `nsfw` property

---

CHANGELOG.md
deno/CHANGELOG.md
package-lock.json
package.json
scripts/deno.mjs

chore(release): 0.16.0 🎉

---

deno/payloads/v8/channel.ts
payloads/v8/channel.ts

discord/discord-api-docs@b9b8db2

refactor(APISticker): remove `preview_asset`

---

deno/rest/v8/webhook.ts
rest/v8/webhook.ts

feat(WebhookMessage): add `GET` route types

---

CHANGELOG.md
deno/CHANGELOG.md
package-lock.json
package.json

chore(release): 0.17.0 🎉

---

CHANGELOG.md
deno/CHANGELOG.md
package-lock.json
package.json

chore(release): 0.18.0 🎉

---

deno/payloads/v8/interactions.ts
payloads/v8/interactions.ts

https://github.com/discord/discord-api-docs/pull/2853

feat(ApplicationCommandOptionType): add `MENTIONABLE` (9)

---

deno/payloads/v8/invite.ts
deno/rest/v8/invite.ts
payloads/v8/invite.ts
rest/v8/invite.ts

https://github.com/discord/discord-api-docs/pull/2858

feat(APIInvite): add `expires_at` field and `with_expiration` param

---

CHANGELOG.md
deno/CHANGELOG.md
package-lock.json
package.json

chore(release): 0.18.1 🎉

---

package-lock.json
package.json

chore: don't install huskies in CI

---

.github/workflows/cicd.yml
.github/workflows/publish-next.yml
package.json

fix: fix autopublish CD

---

deno/payloads/v9/channel.ts
deno/rest/common.ts
deno/rest/v9/channel.ts
payloads/v9/channel.ts
rest/common.ts
rest/v9/channel.ts

Threads part 2...keeping up with API docs
https://github.com/discord/discord-api-docs/pull/3108
https://github.com/discord/discord-api-docs/pull/3126

feat(Threads): add default auto archive and minor tweaks

---

deno/globals.ts
globals.ts

Timezone formatted timestamps!!!!! (but the regex matches)
https://github.com/discord/discord-api-docs/pull/3135
https://github.com/discord/discord-api-docs/pull/3141

feat(FormattingPatterns): add timestamp

---

deno/gateway/v8.ts
deno/gateway/v9.ts
deno/payloads/v8/channel.ts
deno/payloads/v8/interactions.ts
deno/payloads/v9/channel.ts
deno/payloads/v9/interactions.ts
gateway/v8.ts
gateway/v9.ts
payloads/v8/channel.ts
payloads/v8/interactions.ts
payloads/v9/channel.ts
payloads/v9/interactions.ts

This draft documents the Components API which is being added to Messages.
It also includes data for the new Interaction type when buttons are clicked.
I'll be honest, I don't understand a lot of the structure of this, but hopefully this can be collaboratively worked on.
Open to all feedback.

feat(Interactions): components and component interactions

---

deno/globals.ts
globals.ts

fix(FormattingPatterns): fix StyledTimestamp

---

deno/rest/v9/channel.ts
rest/v9/channel.ts

Threads part 3...
https://github.com/discord/discord-api-docs/pull/3162

feat(Threads): add typed thread creation

---

.github/workflows/publish-next.yml

chore: deprecate old @next versions

---

rest/v8/webhook.ts
rest/v9/webhook.ts

in Reference it missing components. so add it.
https://discord.com/developers/docs/resources/webhook#execute-webhook

fix(RESTPostAPIWebhookWithTokenJSONBody): add missing components

---

CHANGELOG.md
deno/CHANGELOG.md
deno/rest/v8/webhook.ts
deno/rest/v9/webhook.ts
package-lock.json
package.json

chore(release): 0.19.0 🎉

---

deno/payloads/v8/auditLog.ts
deno/payloads/v8/channel.ts
deno/payloads/v9/auditLog.ts
deno/payloads/v9/channel.ts
deno/rest/v8/mod.ts
deno/rest/v9/mod.ts
deno/rpc/v8.ts
deno/rpc/v9.ts
deno/utils/v8.ts
deno/utils/v9.ts
payloads/v8/auditLog.ts
payloads/v8/channel.ts
payloads/v9/auditLog.ts
payloads/v9/channel.ts
rest/v8/index.ts
rest/v9/index.ts
rpc/v8.ts
rpc/v9.ts
utils/v8.ts
utils/v9.ts

I think you have heard of https://github.com/discordjs/discord.js/pull/6036, well, I ported the changes here so the names are consistent between the two.
I also didn't update v6 since those don't seem to be changed, but I can update them if requested.
N/a.

refactor: change `xID` to `xId`

---

deno/payloads/v8/permissions.ts
deno/payloads/v9/permissions.ts
payloads/v8/permissions.ts
payloads/v9/permissions.ts

https://github.com/discord/discord-api-docs/pull/3128/commits/03626e1e75e1aecc8580339bff4bd9c9023bf23b
- in https://github.com/discord/discord-api-docs/pull/3128

feat(PermissionFlagsBits): add `UseExternalStickers` (1n << 37n)

---

deno/rest/common.ts
rest/common.ts

https://github.com/discord/discord-api-docs/pull/3128/commits/a02d435ca278e00ff414a2822eba0e34bdfa736a, https://github.com/discord/discord-api-docs/pull/3128/commits/72622604dc6e04169299a0b33f9e19c3b618e9f3
- in https://github.com/discord/discord-api-docs/pull/3128

feat(RESTJSONErrorCodes): add sticker errors

---

CHANGELOG.md
deno/CHANGELOG.md
package-lock.json
package.json

chore(release): 0.20.0 🎉

---

CHANGELOG.md
deno/CHANGELOG.md
package-lock.json
package.json

chore(release): 0.20.1 🎉

---

deno/payloads/v8/_interactions/ping.ts
deno/payloads/v8/interactions.ts
deno/payloads/v9/_interactions/ping.ts
deno/payloads/v9/interactions.ts
payloads/v8/_interactions/ping.ts
payloads/v8/interactions.ts
payloads/v9/_interactions/ping.ts
payloads/v9/interactions.ts

Emergency PR because I did an oopsie.

fix(APIInteraction): bring back Ping type

---

CHANGELOG.md
deno/CHANGELOG.md
package-lock.json
package.json

chore(release): 0.20.2 🎉

---

deno/payloads/v8/_interactions/slashCommands.ts
deno/payloads/v9/_interactions/slashCommands.ts
payloads/v8/_interactions/slashCommands.ts
payloads/v9/_interactions/slashCommands.ts

Reverts discordjs/discord-api-types#169

revert: fix: change resolved index types to string

---

CHANGELOG.md
deno/CHANGELOG.md
package-lock.json
package.json

chore(release): 0.21.0 🎉

---

deno/payloads/v9/auditLog.ts
deno/payloads/v9/channel.ts
deno/rest/v9/channel.ts
deno/rest/v9/guild.ts
deno/rest/v9/mod.ts
payloads/v9/auditLog.ts
payloads/v9/channel.ts
rest/v9/channel.ts
rest/v9/guild.ts
rest/v9/index.ts

* https://github.com/discord/discord-api-docs/pull/3502

feat: thread updates

---

deno/payloads/v8/channel.ts
deno/payloads/v9/channel.ts
payloads/v8/channel.ts
payloads/v9/channel.ts

Type was wrong, now it's right.

fix(MessageComponent): correct type for emoji

---

CHANGELOG.md
deno/CHANGELOG.md
package-lock.json
package.json

chore(release): 0.22.0 🎉

---

deno/payloads/v9/_interactions/base.ts
payloads/v9/_interactions/base.ts

this pr fix a 404 error when you use this package with deno

fix: import causing error 404 on deno

---

deno/payloads/v8/user.ts
deno/payloads/v9/user.ts
payloads/v8/user.ts
payloads/v9/user.ts

* https://github.com/discord/discord-api-docs/pull/3448

feat(APIUser): add `banner` and `accent_color`

---

deno/payloads/v9/channel.ts
deno/rest/v9/channel.ts
payloads/v9/channel.ts
rest/v9/channel.ts

* https://github.com/discord/discord-api-docs/pull/3600

feat(threads): add `invitable`

---

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/SUPPORT.md

Flexes the vanity URL of the Discord server.

chore: Update invite link

---

deno/payloads/v8/auditLog.ts
deno/payloads/v9/auditLog.ts
payloads/v8/auditLog.ts
payloads/v9/auditLog.ts

This should be a string!
https://discord.com/developers/docs/resources/audit-log#audit-log-change-object-audit-log-change-key

fix(auditLog): Correct nickname type

---

deno/payloads/v8/channel.ts
deno/payloads/v9/channel.ts
payloads/v8/channel.ts
payloads/v9/channel.ts

this might change or not actually ship, so don't merge yet
* https://github.com/discord/discord-api-docs/pull/3651

feat(MessageType): add ContextMenuCommand and rename ApplicationCommand to ChatInputCommand

---

deno/payloads/v8/_interactions/applicationCommands.ts
deno/payloads/v9/_interactions/applicationCommands.ts
payloads/v8/_interactions/applicationCommands.ts
payloads/v9/_interactions/applicationCommands.ts

https://github.com/discord/discord-api-docs/pull/3524

feat(APIApplicationCommand): add `version` field

---

CHANGELOG.md
deno/CHANGELOG.md
package-lock.json
package.json

Releasing to allow https://github.com/discordjs/builders/pull/29 to continue

chore(release): 0.23.0 🎉

---

CHANGELOG.md
deno/CHANGELOG.md
package-lock.json
package.json

chore(release): 0.23.1 🎉

---

deno/payloads/v8/permissions.ts
deno/payloads/v9/permissions.ts
payloads/v8/permissions.ts
payloads/v9/permissions.ts

* https://github.com/discord/discord-api-docs/pull/3805

feat(PermissionFlagsBits): add `StartEmbeddedActivities`

---

deno/payloads/v8/channel.ts
deno/payloads/v9/channel.ts
payloads/v8/channel.ts
payloads/v9/channel.ts

Adds `APIAttachment#ephemeral`
- discord/discord-api-docs#3833

feat(APIAttachment): add ephemeral field

---

deno/payloads/v9/permissions.ts
payloads/v9/permissions.ts

* https://github.com/discord/discord-api-docs/pull/3672

feat(PermissionFlagBits): update thread permissions

---

deno/payloads/v8/channel.ts
deno/payloads/v9/channel.ts
payloads/v8/channel.ts
payloads/v9/channel.ts

- discord/discord-api-docs#3875

fix(APISelectMenuComponenet): make options field optional

---

deno/payloads/v8/guild.ts
deno/payloads/v8/permissions.ts
deno/payloads/v9/guild.ts
deno/payloads/v9/permissions.ts
deno/rest/v8/guild.ts
deno/rest/v9/guild.ts
payloads/v8/guild.ts
payloads/v8/permissions.ts
payloads/v9/guild.ts
payloads/v9/permissions.ts
rest/v8/guild.ts
rest/v9/guild.ts

Adds support for role icons.
- https://github.com/discord/discord-api-docs/pull/3847

feat: Add role icons

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/3840

feat(RESTJSONErrorCodes): add error 50101

---

deno/payloads/v9/_interactions/applicationCommands.ts
payloads/v9/_interactions/applicationCommands.ts

Closes #187
- https://github.com/discord/discord-api-docs/commit/73b9aae8a1a5bbf3a54b29588284f3dd57787b69

types: add `parent_id` and `thread_metadata` fields to resolved channels

---

deno/payloads/v8/guild.ts
deno/payloads/v9/guild.ts
payloads/v8/guild.ts
payloads/v9/guild.ts

- https://github.com/discord/discord-api-docs/pull/3081

feat(APIGuildMember): add per guild avatars

---

deno/payloads/v8/user.ts
deno/payloads/v9/user.ts
payloads/v8/user.ts
payloads/v9/user.ts

- https://github.com/discord/discord-api-docs/pull/3903

feat(UserFlags): add `BOT_HTTP_INTERACTIONS` flag

---

deno/payloads/v8/application.ts
deno/payloads/v9/application.ts
payloads/v8/application.ts
payloads/v9/application.ts

- https://github.com/discord/discord-api-docs/pull/3999

feat(ApplicationFlags): add message content intent flags

---

deno/payloads/v8/guild.ts
deno/payloads/v9/guild.ts
payloads/v8/guild.ts
payloads/v9/guild.ts

- https://github.com/discord/discord-api-docs/pull/3977

feat(GuildSystemChannelFlags): add suppress member join sticker replies flag

---

deno/payloads/v8/gateway.ts
deno/payloads/v9/gateway.ts
payloads/v8/gateway.ts
payloads/v9/gateway.ts

- https://github.com/discord/discord-api-docs/pull/3877

feat(ActivityFlags): add new flags

---

deno/payloads/v8/_interactions/_applicationCommands/chatInput.ts
deno/payloads/v9/_interactions/_applicationCommands/chatInput.ts
payloads/v8/_interactions/_applicationCommands/chatInput.ts
payloads/v9/_interactions/_applicationCommands/chatInput.ts

- https://github.com/discord/discord-api-docs/pull/3967

feat: add max/min option for number-based options

---

deno/rest/common.ts
rest/common.ts

adds the funny maze error code no upstream pr

feat: add maze api error

---

deno/payloads/v8/_interactions/autocomplete.ts
deno/payloads/v9/_interactions/autocomplete.ts
payloads/v8/_interactions/autocomplete.ts
payloads/v9/_interactions/autocomplete.ts

fix: correct types for autocomplete interaction data

---

deno/rest/v9/channel.ts
rest/v9/channel.ts

- https://github.com/discord/discord-api-docs/commit/d56be860c5dd4c04e80337556d82eb3a04f971a2

feat(RESTPostAPIChannelThreadsJSONBody): add `rate_limit_per_user`

---

CHANGELOG.md
deno/CHANGELOG.md
package-lock.json
package.json

chore(release): 0.25.0 🎉

---

CHANGELOG.md
deno/CHANGELOG.md
package-lock.json
package.json

chore(release): 0.25.1 🎉

---

CHANGELOG.md
deno/CHANGELOG.md
package-lock.json
package.json

chore(release): 0.25.2 🎉

---

deno/payloads/v8/auditLog.ts
deno/payloads/v9/auditLog.ts
payloads/v8/auditLog.ts
payloads/v9/auditLog.ts

- https://github.com/discord/discord-api-docs/pull/4152

feat(APIAuditLog): add `guild_scheduled_events` prop

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/4212

feat: Add API error code `50055`

---

deno/rest/common.ts
rest/common.ts

https://github.com/discord/discord-api-docs/pull/4214

feat(RESTJSONErrorCodes): add error 20029

---

deno/payloads/v8/oauth2.ts
deno/payloads/v9/oauth2.ts
deno/rest/v8/mod.ts
deno/rest/v8/user.ts
deno/rest/v9/mod.ts
deno/rest/v9/user.ts
payloads/v8/oauth2.ts
payloads/v9/oauth2.ts
rest/v8/index.ts
rest/v8/user.ts
rest/v9/index.ts
rest/v9/user.ts

- https://github.com/discord/discord-api-docs/pull/4204

feat: add support for user guild member read oauth2 scope and route

---

deno/payloads/v8/invite.ts
deno/payloads/v9/invite.ts
payloads/v8/invite.ts
payloads/v9/invite.ts

* https://github.com/discord/discord-api-docs/pull/3659

fix(APIInvite): channel can be null

---

deno/gateway/v9.ts
gateway/v9.ts

- https://github.com/discord/discord-api-docs/pull/4228

feat(GatewayThreadMemberUpdateDispatchData): add `guild_id` extra field

---

deno/payloads/v8/sticker.ts
deno/payloads/v9/sticker.ts
payloads/v8/sticker.ts
payloads/v9/sticker.ts

- https://github.com/discord/discord-api-docs/pull/4245

fix(StickerPack): Optional `banner_asset_id`

---

deno/payloads/v8/guild.ts
deno/payloads/v8/permissions.ts
deno/payloads/v9/guild.ts
deno/payloads/v9/permissions.ts
payloads/v8/guild.ts
payloads/v8/permissions.ts
payloads/v9/guild.ts
payloads/v9/permissions.ts

- https://github.com/discord/discord-api-docs/pull/4075

feat(APIGuildMember): add guild timeouts

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/4241

feat: Add API error code 50109

---

CHANGELOG.md
deno/CHANGELOG.md
package-lock.json
package.json

chore(release): 0.26.0 🎉

---

deno/payloads/v8/application.ts
deno/payloads/v9/application.ts
payloads/v8/application.ts
payloads/v9/application.ts

- https://github.com/discordjs/discord-api-types/pull/271#issuecomment-1001009531
- https://github.com/discord/discord-api-docs/pull/4248

feat(ApplicationFlags): add embedded application flags

---

deno/payloads/v8/_interactions/_applicationCommands/_chatInput/integer.ts
deno/payloads/v8/_interactions/_applicationCommands/_chatInput/number.ts
deno/payloads/v8/_interactions/_applicationCommands/chatInput.ts
deno/payloads/v9/_interactions/_applicationCommands/_chatInput/integer.ts
deno/payloads/v9/_interactions/_applicationCommands/_chatInput/number.ts
deno/payloads/v9/_interactions/_applicationCommands/chatInput.ts
payloads/v8/_interactions/_applicationCommands/_chatInput/integer.ts
payloads/v8/_interactions/_applicationCommands/_chatInput/number.ts
payloads/v8/_interactions/_applicationCommands/chatInput.ts
payloads/v9/_interactions/_applicationCommands/_chatInput/integer.ts
payloads/v9/_interactions/_applicationCommands/_chatInput/number.ts
payloads/v9/_interactions/_applicationCommands/chatInput.ts

fix(APIApplicationCommandOption): correct type for integer and number

---

deno/rest/v8/mod.ts
deno/rest/v9/mod.ts
rest/v8/index.ts
rest/v9/index.ts

Adds a new route base for guild scheduled events.
https://github.com/discordjs/discord.js/blob/main/packages/discord.js/src/util/Options.js#L159

feat(RouteBases): add base for guild scheduled events

---

deno/payloads/v8/user.ts
deno/payloads/v9/user.ts
payloads/v8/user.ts
payloads/v9/user.ts

feat(UserFlags): add `Spammer` flag

---

deno/payloads/v8/guild.ts
deno/payloads/v9/guild.ts
payloads/v8/guild.ts
payloads/v9/guild.ts

- https://github.com/discord/discord-api-docs/pull/4278

feat(APIGuildPreview): add `stickers`

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/4302

feat(RESTJSONErrorCodes): add error code 50086

---

deno/rest/v8/channel.ts
deno/rest/v8/webhook.ts
deno/rest/v9/channel.ts
deno/rest/v9/webhook.ts
rest/v8/channel.ts
rest/v8/webhook.ts
rest/v9/channel.ts
rest/v9/webhook.ts

- https://github.com/discord/discord-api-docs/pull/4356

feat(RESTAPIPostChannelMessage, RESTAPIPostWebhookMessage): add flags for creation

---

deno/payloads/v9/channel.ts
payloads/v9/channel.ts

- https://github.com/discord/discord-api-docs/commit/53ee0109b874bde5ec2316379bf266bb332630a0

feat(APIThreadMetadata): add `create_timestamp` field

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/4366

feat(RESTJSONErrorCodes): add error 50068

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/4381

feat(RESTJSONErrorCodes): add error 30046

---

deno/rest/common.ts
rest/common.ts

This error code is already in the docs, looks like it was missed.

feat(RESTJSONErrorCodes): add error 30042

---

deno/payloads/v8/guildScheduledEvent.ts
deno/payloads/v9/guildScheduledEvent.ts
deno/rest/v8/guildScheduledEvent.ts
deno/rest/v9/guildScheduledEvent.ts
payloads/v8/guildScheduledEvent.ts
payloads/v9/guildScheduledEvent.ts
rest/v8/guildScheduledEvent.ts
rest/v9/guildScheduledEvent.ts

- https://github.com/discord/discord-api-docs/pull/4380

feat(APIScheduledEvent): add `image` prop

---

deno/payloads/v8/user.ts
deno/payloads/v9/user.ts
payloads/v8/user.ts
payloads/v9/user.ts

Talked about in Discord https://discord.com/channels/222078108977594368/682166281826598932/937688056801132544
Causes an issue with discord.js:
-  https://github.com/discordjs/discord.js/issues/7374
Closes https://github.com/discordjs/discord.js/issues/7374

refactor(userflags): remove `None`

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/4444

feat(RESTJSONErrorCodes): add error 40004

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/4484

feat(RESTJSONErrorCodes): add error 40060

---

.github/workflows/create-pr-for-release-and-publish.yml

ci: run publish workflow every Monday and Thursday

---

deno/payloads/v10/invite.ts
deno/payloads/v10/stageInstance.ts
deno/payloads/v9/invite.ts
deno/payloads/v9/stageInstance.ts
payloads/v10/invite.ts
payloads/v10/stageInstance.ts
payloads/v9/invite.ts
payloads/v9/stageInstance.ts

Each commit corresponds to each pull request listed below, respectively
- https://github.com/discord/discord-api-docs/pull/4296
- https://github.com/discord/discord-api-docs/pull/4479

chore(APIInviteStageInstance, APIStageInstance): deprecate stage discovery

---

deno/payloads/common.ts
payloads/common.ts

- https://github.com/discord/discord-api-docs/pull/4555

refactor(PermissionFlagsBits): rename `StartEmbeddedActivities` to `UseEmbeddedActivities`

---

package.json

Just like https://github.com/discordjs/discord.js/pull/7598, this is needed for users that want to use module/moduleResolution: NodeNext with TS

feat: add support for TS module: NodeNext

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

- https://github.com/discord/discord-api-docs/pull/4551

docs(APISelectMenuComponent): update `placeholder` max to 150

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/4530

feat(RESTJSONErrorCodes): add error `10065`

---

deno/payloads/v10/voice.ts
deno/payloads/v9/voice.ts
payloads/v10/voice.ts
payloads/v9/voice.ts

- https://github.com/discord/discord-api-docs/pull/4565

fix(GatewayVoiceState): some fields are optional instead of nullable

---

deno/payloads/v10/guildScheduledEvent.ts
deno/payloads/v10/sticker.ts
deno/payloads/v9/guildScheduledEvent.ts
deno/payloads/v9/sticker.ts
deno/rest/v10/guildScheduledEvent.ts
deno/rest/v9/guildScheduledEvent.ts
payloads/v10/guildScheduledEvent.ts
payloads/v10/sticker.ts
payloads/v9/guildScheduledEvent.ts
payloads/v9/sticker.ts
rest/v10/guildScheduledEvent.ts
rest/v9/guildScheduledEvent.ts

Each commit contains more useful information on what was actually changed
- https://github.com/discord/discord-api-docs/pull/4564

refactor: make things optional and nullable where applicable

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/4533

refactor(RESTJSONErrorCodes): update error `50008` key

---

deno/rest/common.ts
rest/common.ts

fix(RESTJSONErrorCodes): typo in error `30046`

---

deno/payloads/v10/stageInstance.ts
deno/payloads/v9/stageInstance.ts
payloads/v10/stageInstance.ts
payloads/v9/stageInstance.ts

- https://github.com/discord/discord-api-docs/pull/4583

feat(APIStageInstance): add `guild_scheduled_event_id`

---

deno/payloads/v10/invite.ts
deno/payloads/v8/invite.ts
deno/payloads/v9/invite.ts
payloads/v10/invite.ts
payloads/v8/invite.ts
payloads/v9/invite.ts

This also fixes the guild on invites to be accurate to the example in the docs.
- https://github.com/discord/discord-api-docs/pull/4493

feat(APIInviteGuild): add boost count

---

deno/payloads/v10/voice.ts
deno/payloads/v9/voice.ts
payloads/v10/voice.ts
payloads/v9/voice.ts

reverts #345 
https://github.com/discord/discord-api-docs/pull/4641

revert: fix(GatewayVoiceState): some fields are optional instead of nullable

---

.github/auto_assign.yml
.github/labeler.yml
.github/labels.yml
.github/workflows/pr-automation.yml

Basically shameless copy from d.js

ci: automatic PR triage

---

deno/v10.ts
scripts/deno.mjs

Woops, I forgot to do this for API v10

chore(deno): give deno the v10 exports they desire

---

deno/payloads/v10/user.ts
deno/payloads/v9/user.ts
payloads/v10/user.ts
payloads/v9/user.ts

- https://github.com/discord/discord-api-docs/pull/4685

docs(UserFlags): update misleading `Hypesquad` description

---

deno/payloads/v10/_interactions/_applicationCommands/_chatInput/base.ts
deno/payloads/v10/_interactions/_applicationCommands/_chatInput/shared.ts
deno/payloads/v10/_interactions/applicationCommands.ts
deno/payloads/v9/_interactions/_applicationCommands/_chatInput/base.ts
deno/payloads/v9/_interactions/_applicationCommands/_chatInput/shared.ts
deno/payloads/v9/_interactions/applicationCommands.ts
payloads/v10/_interactions/_applicationCommands/_chatInput/base.ts
payloads/v10/_interactions/_applicationCommands/_chatInput/shared.ts
payloads/v10/_interactions/applicationCommands.ts
payloads/v9/_interactions/_applicationCommands/_chatInput/base.ts
payloads/v9/_interactions/_applicationCommands/_chatInput/shared.ts
payloads/v9/_interactions/applicationCommands.ts

- https://github.com/discord/discord-api-docs/pull/4710

refactor(APIApplicationCommand): nullable localization fields

---

deno/payloads/v10/application.ts
deno/payloads/v10/guild.ts
deno/payloads/v9/application.ts
deno/payloads/v9/guild.ts
payloads/v10/application.ts
payloads/v10/guild.ts
payloads/v9/application.ts
payloads/v9/guild.ts

Not completely sure if it was completely removed on v9 and I am not able to test it
- https://github.com/discord/discord-api-docs/commit/6ef4712c4351ac498591000e7e5251f722e47472
- https://github.com/discord/discord-api-docs/pull/4686

refactor: remove `summary` from applications

---

deno/payloads/v10/_interactions/applicationCommands.ts
deno/payloads/v9/_interactions/applicationCommands.ts
payloads/v10/_interactions/applicationCommands.ts
payloads/v9/_interactions/applicationCommands.ts

- https://github.com/discord/discord-api-docs/pull/4724

docs(APIApplicationCommand): use the new regex

---

deno/payloads/v10/guild.ts
deno/payloads/v9/guild.ts
payloads/v10/guild.ts
payloads/v9/guild.ts

- https://github.com/discord/discord-api-docs/pull/4803

refactor(APIGuildIntegration): make `enabled` optional

---

README.md
deno/README.md
website/docs/Introduction.mdx
website/versioned_docs/version-0.33.0/Introduction.mdx

chore: fix docs typo

---

deno/rest/v10/guild.ts
deno/rest/v9/guild.ts
rest/v10/guild.ts
rest/v9/guild.ts

~~The `flags` field in the thread payload will be addressed in #415~~
- https://github.com/discord/discord-api-docs/pull/4867

chore(guildChannel): update post body fields

---

deno/rest/v10/interactions.ts
deno/rest/v9/interactions.ts
rest/v10/interactions.ts
rest/v9/interactions.ts

Fixes a type issue reported by @gc 

fix(RESTPostAPIApplicationGuildCommands): correct types due to unions

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/4982

feat(RESTJSONErrorCodes): add error `50600`

---

deno/payloads/v10/_interactions/_applicationCommands/permissions.ts
deno/payloads/v9/_interactions/_applicationCommands/permissions.ts
payloads/v10/_interactions/_applicationCommands/permissions.ts
payloads/v9/_interactions/_applicationCommands/permissions.ts

- https://github.com/discord/discord-api-docs/pull/4872

docs: clarify that permissions can apply on application-level

---

deno/gateway/v10.ts
deno/gateway/v9.ts
gateway/v10.ts
gateway/v9.ts

fix(GatewayGuildCreateDispatch): add extra fields that were missing

---

.prettierignore
scripts/bump-website-version.mjs
website/docusaurus.config.js

chore(docs): minify api-typedoc generated json

---

website/docs/Contributing.mdx
website/versioned_docs/version-0.33.0/Contributing.mdx
website/versioned_docs/version-0.33.1/Contributing.mdx
website/versioned_docs/version-0.33.2/Contributing.mdx

docs: fix line highlighting for contributing guide

---

.vscode/settings.json
website/docs/Contributing.mdx
website/versioned_docs/version-0.33.0/Contributing.mdx
website/versioned_docs/version-0.33.1/Contributing.mdx
website/versioned_docs/version-0.33.2/Contributing.mdx

docs: fix typo

---

deno/rest/common.ts
rest/common.ts

- discord/discord-api-docs#5024

feat(RESTJSONErrorCodes): add error `30052`

---

package.json

chore: showcase website in package.json

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/5018

feat(RESTJSONErrorCodes): add 220003 error

---

deno/rest/common.ts
deno/rest/v10/guild.ts
deno/rest/v10/mod.ts
deno/rest/v9/guild.ts
deno/rest/v9/mod.ts
rest/common.ts
rest/v10/guild.ts
rest/v10/index.ts
rest/v9/guild.ts
rest/v9/index.ts

- discord/discord-api-docs#5031
- discord/discord-api-docs#5032

feat: add guild mfa endpoint and error `50017`

---

website/docs/Contributing.mdx
website/versioned_docs/version-0.33.2/Contributing.mdx
website/versioned_docs/version-0.33.3/Contributing.mdx
website/versioned_docs/version-0.33.4/Contributing.mdx
website/versioned_docs/version-0.33.5/Contributing.mdx

docs: fix some grammar mistakes

---

website/src/components/Home/HeadTags.tsx

Lighthouse score thirst
@favna can you take a look and lmk if this is the correct React way?

docs: lazy load JetBrains mono font

---

deno/payloads/v10/user.ts
deno/payloads/v8/user.ts
deno/payloads/v9/user.ts
payloads/v10/user.ts
payloads/v8/user.ts
payloads/v9/user.ts

Adds `Quarantined (1 << 44)` flag to UserFlags.

feat(UserFlags): add `Quarantined` flag

---

deno/payloads/v10/_interactions/base.ts
deno/payloads/v9/_interactions/base.ts
payloads/v10/_interactions/base.ts
payloads/v9/_interactions/base.ts

Tiny because it includes only docs, but a important thing
- https://github.com/discord/discord-api-docs/pull/5140

docs(APIMessageInteraction): `name` now includes more info

---

website/docs/Contributing.mdx

Looks like my last PR didn't make Prettier happy *whoops*

chore: resolve ci error

---

deno/rest/common.ts
rest/common.ts

- discord/discord-api-docs#5175

feat(RESTJSONErrorCodes): add error `30032`

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/5189

feat(RESTJSONErrorCodes): add error `50146`

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/5200

feat(RESTJSONErrorCodes): add error `30034`

---

website/docs/Contributing.mdx

docs: update discord channel name again

---

deno/gateway/v10.ts
deno/gateway/v9.ts
gateway/v10.ts
gateway/v9.ts

…er_ids
the previous type incorrectly required `limit` to be present with `user_ids` queries

fix(GatewayRequestGuildMembersData): limit being required with user_ids

---

deno/gateway/v10.ts
deno/gateway/v9.ts
gateway/v10.ts
gateway/v9.ts

- https://github.com/discord/discord-api-docs/pull/5282

feat(GatewayReadyDispatchData): add `resume_gateway_url`

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
deno/rest/v10/channel.ts
deno/rest/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts
rest/v10/channel.ts
rest/v9/channel.ts

- discord/discord-api-docs#5322

refactor(ChannelType): rename news & thread types

---

deno/payloads/v10/application.ts
deno/payloads/v9/application.ts
payloads/v10/application.ts
payloads/v9/application.ts

- https://github.com/discord/discord-api-docs/pull/5222

feat(ApplicationFlags): add `ApplicationCommandBadge`

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

fix(GuildChannelType): add missing `GuildCategory` type

---

deno/payloads/v10/guild.ts
deno/payloads/v9/guild.ts
payloads/v10/guild.ts
payloads/v9/guild.ts

- https://github.com/discord/discord-api-docs/pull/5269

feat(GuildFeature): add `InvitesDisabled`

---

deno/payloads/v10/user.ts
deno/payloads/v9/user.ts
payloads/v10/user.ts
payloads/v9/user.ts

- https://github.com/discord/discord-api-docs/pull/5265
- https://github.com/discord/discord-api-docs/pull/5306
- https://github.com/discord/discord-api-docs/pull/5355
- https://github.com/discord/discord-api-docs/pull/5396

feat(ConnectionService): add new connections

---

deno/payloads/v10/user.ts
deno/payloads/v9/user.ts
payloads/v10/user.ts
payloads/v9/user.ts

- https://github.com/discord/discord-api-docs/pull/5259

feat(APIConnection): add `two_way_link`

---

deno/rest/common.ts
rest/common.ts

- discord/discord-api-docs#5508

feat(RESTJSONErrorCodes): add error `50073`

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

* https://github.com/discord/discord-api-docs/pull/5556

fix(ChannelType): publicthreads can be in forum channels

---

deno/payloads/v10/user.ts
deno/payloads/v9/user.ts
payloads/v10/user.ts
payloads/v9/user.ts

- https://github.com/discord/discord-api-docs/pull/5568

feat(UserPremiumType): add `NitroBasic`

---

deno/gateway/common.ts
deno/gateway/v10.ts
deno/gateway/v8.ts
deno/gateway/v9.ts
deno/payloads/v10/gateway.ts
deno/payloads/v9/gateway.ts
gateway/common.ts
gateway/v10.ts
gateway/v8.ts
gateway/v9.ts
payloads/v10/gateway.ts
payloads/v9/gateway.ts

fix(docs): update gateway documentation links

---

deno/payloads/v9/user.ts
payloads/v9/user.ts

https://github.com/discordjs/discord-api-types/pull/624#issuecomment-1299083615 (it was not intentional)

docs: remove ~

---

deno/rest/v10/channel.ts
deno/rest/v9/channel.ts
rest/v10/channel.ts
rest/v9/channel.ts

- https://github.com/discord/discord-api-docs/pull/5559

docs: add limits for tags in forums

---

deno/payloads/v10/user.ts
deno/payloads/v9/user.ts
payloads/v10/user.ts
payloads/v9/user.ts

- discord/discord-api-docs#5619

feat(UserFlags): add `ActiveDeveloper`

---

deno/rest/v9/channel.ts
rest/v9/channel.ts

docs(RESTGetAPIChannelThreadsResult): Update deprecation URL

---

.github/auto_assign.yml
.github/workflows/pr-automation.yml

This pull request assigns reviewers even on draft pull requests.

ci: Assign reviewers on drafts

---

deno/payloads/v10/user.ts
deno/payloads/v9/user.ts
payloads/v10/user.ts
payloads/v9/user.ts

* https://github.com/discord/discord-api-docs/pull/5695

chore(UserFlags): update certified moderator description

---

deno/payloads/v10/application.ts
deno/payloads/v10/oauth2.ts
deno/payloads/v10/user.ts
deno/payloads/v9/application.ts
deno/payloads/v9/oauth2.ts
deno/payloads/v9/user.ts
deno/rest/v10/application.ts
deno/rest/v10/mod.ts
deno/rest/v10/user.ts
deno/rest/v9/application.ts
deno/rest/v9/mod.ts
deno/rest/v9/user.ts
payloads/v10/application.ts
payloads/v10/oauth2.ts
payloads/v10/user.ts
payloads/v9/application.ts
payloads/v9/oauth2.ts
payloads/v9/user.ts
rest/v10/application.ts
rest/v10/index.ts
rest/v10/user.ts
rest/v9/application.ts
rest/v9/index.ts
rest/v9/user.ts

- discord/discord-api-docs#5668

feat: add role connections

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/5643

feat(Locale): add Indonesian locale

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
deno/rest/v10/channel.ts
deno/rest/v10/guild.ts
deno/rest/v9/channel.ts
deno/rest/v9/guild.ts
payloads/v10/channel.ts
payloads/v9/channel.ts
rest/v10/channel.ts
rest/v10/guild.ts
rest/v9/channel.ts
rest/v9/guild.ts

* https://github.com/discord/discord-api-docs/pull/5693

feat(APIGuildForumChannel): add `default_forum_layout`

---

deno/payloads/v10/application.ts
deno/payloads/v9/application.ts
payloads/v10/application.ts
payloads/v9/application.ts

docs(ApplicationFlags): add descriptions to each flag

---

deno/rest/common.ts
rest/common.ts

- discord/discord-api-docs#5777

feat(RESTJSONErrorCodes): add error `30058`

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/5626

feat(RESTJSONErrorCodes): add error `50067`

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

- discord/discord-api-docs#5815
- discord/discord-api-docs#5826

feat(MessageType): add missing types

---

deno/payloads/v10/channel.ts
deno/payloads/v10/guild.ts
deno/payloads/v10/permissions.ts
deno/payloads/v9/channel.ts
deno/payloads/v9/guild.ts
deno/payloads/v9/permissions.ts
deno/rest/common.ts
payloads/v10/channel.ts
payloads/v10/guild.ts
payloads/v10/permissions.ts
payloads/v9/channel.ts
payloads/v9/guild.ts
payloads/v9/permissions.ts
rest/common.ts

- discord/discord-api-docs#5724

feat: role subscriptions

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
deno/rest/v10/channel.ts
deno/rest/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts
rest/v10/channel.ts
rest/v9/channel.ts

- https://github.com/discord/discord-api-docs/pull/5834

feat(APIThreadMember): add support for thread member pagination

---

deno/payloads/v10/sticker.ts
deno/payloads/v9/sticker.ts
deno/rest/v10/mod.ts
deno/rest/v10/sticker.ts
deno/rest/v9/mod.ts
deno/rest/v9/sticker.ts
payloads/v10/sticker.ts
payloads/v9/sticker.ts
rest/v10/index.ts
rest/v10/sticker.ts
rest/v9/index.ts
rest/v9/sticker.ts

- discord/discord-api-docs#5833

feat(StickerFormatType): add `GIF`

---

deno/payloads/v10/guild.ts
deno/payloads/v9/guild.ts
payloads/v10/guild.ts
payloads/v9/guild.ts

- discord/discord-api-docs#5701

fix(GuildIntegration): `enabled` and `user` are present on bots

---

deno/rest/common.ts
rest/common.ts

- discord/discord-api-docs#5746

feat(RESTJSONErrorCodes): add error `50091`

---

deno/payloads/v10/user.ts
deno/payloads/v9/user.ts
payloads/v10/user.ts
payloads/v9/user.ts

* https://github.com/discord/discord-api-docs/pull/5602

feat(ConnectionService): add TikTok

---

deno/payloads/v10/permissions.ts
deno/payloads/v9/permissions.ts
payloads/v10/permissions.ts
payloads/v9/permissions.ts

- discord/discord-api-docs#5771

feat(APIRoleTags): add `guild_connections`

---

deno/payloads/v10/channel.ts
deno/payloads/v10/guild.ts
payloads/v10/channel.ts
payloads/v10/guild.ts

This pull request adds the role subscription data and respective system channel flags.
- https://github.com/discord/discord-api-docs/pull/5828

feat: Add role subscription data and system channel flags

---

.github/labels.yml

A good use of this label would be easily identifying pull requests that are not waiting for changes from Discord.

chore: Add blocked label

---

deno/payloads/v10/application.ts
deno/payloads/v9/application.ts
payloads/v10/application.ts
payloads/v9/application.ts

- discord/discord-api-docs#5854

docs(APIApplicationRoleConnectionMetadata): specify lower bound of fields

---

deno/payloads/v10/guild.ts
deno/payloads/v9/guild.ts
payloads/v10/guild.ts
payloads/v9/guild.ts

- https://github.com/discord/discord-api-docs/pull/5874

feat(APIGuildMember): add support for guild member flags

---

deno/gateway/v10.ts
deno/gateway/v9.ts
gateway/v10.ts
gateway/v9.ts

- discord/discord-api-docs#5849

feat(GatewayDispatchEvents): add `GuildAuditLogEntryCreate`

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

- discord/discord-api-docs#5910

feat(MessageType): add `SuppressNotifications`

---

deno/gateway/v10.ts
deno/gateway/v9.ts
gateway/v10.ts
gateway/v9.ts

fix(GatewayDispatchPayload): add missing GuildAuditLogEntry

---

deno/payloads/v10/guild.ts
payloads/v10/guild.ts

`SupressRoleSubscriptionPurchaseNotifications` -> `SuppressRoleSubscriptionPurchaseNotifications`

fix(GuildSystemChannelFlags): "suppress" typo

---

deno/rest/common.ts
rest/common.ts

- discord/discord-api-docs#5923

feat(RESTJSONErrorCodes): add error `30061`

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/5867

feat(RESTJSONErrorCodes): add error `30011`

---

deno/payloads/v10/user.ts
deno/payloads/v9/user.ts
payloads/v10/user.ts
payloads/v9/user.ts

- https://github.com/discord/discord-api-docs/pull/5876

feat(ConnectionService): add `instagram`

---

deno/rest/v10/mod.ts
deno/rest/v9/mod.ts
rest/v10/index.ts
rest/v9/index.ts

- discord/discord-api-docs#5856

feat(CDNRoutes): add `storePageAsset()`

---

deno/rest/v10/sticker.ts
deno/rest/v9/sticker.ts
rest/v10/sticker.ts
rest/v9/sticker.ts

- discord/discord-api-docs#5852

docs(RESTPostAPIGuildStickerFormDataBody): clarify constraints

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/5930

feat(RESTJSONErrorCodes): add error `30060`

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

https://github.com/discord/discord-api-docs/pull/5927/commits/195a98ebd6562fa47dba411fea59220c84d4b534 removed this from the documentation.
- https://github.com/discord/discord-api-docs/pull/5927

fix: `StageRaiseHand` should be unstable

---

deno/payloads/v10/autoModeration.ts
deno/payloads/v9/autoModeration.ts
payloads/v10/autoModeration.ts
payloads/v9/autoModeration.ts

- discord/discord-api-docs#5909

docs(AutoModerationRuleTriggerType): increase keyword limits

---

deno/payloads/v10/application.ts
deno/payloads/v10/channel.ts
deno/payloads/v10/guild.ts
deno/payloads/v10/user.ts
deno/payloads/v9/application.ts
deno/payloads/v9/channel.ts
deno/payloads/v9/guild.ts
deno/payloads/v9/user.ts
payloads/v10/application.ts
payloads/v10/channel.ts
payloads/v10/guild.ts
payloads/v10/user.ts
payloads/v9/application.ts
payloads/v9/channel.ts
payloads/v9/guild.ts
payloads/v9/user.ts

i think i got all of them, verify that these are correct tho

feat: add various new flags

---

deno/payloads/v10/guild.ts
deno/payloads/v9/guild.ts
deno/rest/v10/user.ts
deno/rest/v9/user.ts
payloads/v10/guild.ts
payloads/v9/guild.ts
rest/v10/user.ts
rest/v9/user.ts

- discord/discord-api-docs#5628

feat(RESTGetAPICurrentUserGuildsQuery): add `with_counts`

---

deno/rest/v10/guild.ts
deno/rest/v9/guild.ts
rest/v10/guild.ts
rest/v9/guild.ts

- discord/discord-api-docs#5978

feat(RESTPostAPIGuildChannelJSONBody): add `default_thread_rate_limit_per_user`

---

website/src/css/discordjs.scss

| Old | New |
| :-: | :-: |
| ![image](https://user-images.githubusercontent.com/24852502/230169501-151498bc-dac1-4ca6-a90b-5f8d02ae8fe3.png) | ![image](https://user-images.githubusercontent.com/24852502/230169621-c2f22097-504f-4613-8e8b-0005f11e8785.png) |
Backport from https://github.com/sapphiredev/website/pull/232
N/a

chore(docsearch): increase contrast for hits in dark mode

---

deno/payloads/v10/_interactions/applicationCommands.ts
deno/payloads/v10/_interactions/base.ts
deno/payloads/v10/_interactions/messageComponents.ts
deno/payloads/v9/_interactions/applicationCommands.ts
deno/payloads/v9/_interactions/base.ts
deno/payloads/v9/_interactions/messageComponents.ts
payloads/v10/_interactions/applicationCommands.ts
payloads/v10/_interactions/base.ts
payloads/v10/_interactions/messageComponents.ts
payloads/v9/_interactions/applicationCommands.ts
payloads/v9/_interactions/base.ts
payloads/v9/_interactions/messageComponents.ts

- discord/discord-api-docs#6051

feat(APIBaseInteraction): add `channel`

---

deno/payloads/v10/application.ts
deno/payloads/v9/application.ts
payloads/v10/application.ts
payloads/v9/application.ts

- discord/discord-api-docs#6021

docs(ApplicationFlags): `ApplicationAutoModerationRuleCreateBadge` is no longer unstable

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/5948

feat(RESTJSONErrorCodes): add error `50163`

---

deno/payloads/common.ts
payloads/common.ts

Suggested in https://github.com/discordjs/discord-api-types/pull/749#discussion_r1167341108
https://discord.com/developers/docs/topics/permissions#permissions-bitwise-permission-flags

docs(PermissionFlagsBits): add descriptions

---

deno/rest/v10/channel.ts
deno/rest/v9/channel.ts
rest/v10/channel.ts
rest/v9/channel.ts

For a while now, this no longer requires Boosts.

docs(RESTPostAPIChannelMessagesThreadsJSONBody): Remove 3/7-day requirement text

---

deno/gateway/v10.ts
deno/gateway/v9.ts
gateway/v10.ts
gateway/v9.ts

- discord/discord-api-docs#6102
- discord/discord-api-docs#6296

feat(GatewayMessageReactionAddDispatch): add `message_author_id`

---

deno/payloads/v10/permissions.ts
deno/payloads/v9/permissions.ts
payloads/v10/permissions.ts
payloads/v9/permissions.ts

* https://github.com/discord/discord-api-docs/pull/6269

feat(APIRole): role flags

---

deno/payloads/v10/auditLog.ts
deno/payloads/v9/auditLog.ts
payloads/v10/auditLog.ts
payloads/v9/auditLog.ts

- https://github.com/discord/discord-api-docs/pull/6071

feat(AuditLogEvent): Add creator monetisation events

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

- discord/discord-api-docs#6272

feat(APIAttachment): add `flags`

---

deno/payloads/v10/user.ts
deno/payloads/v9/user.ts
deno/rest/v10/mod.ts
deno/rest/v9/mod.ts
payloads/v10/user.ts
payloads/v9/user.ts
rest/v10/index.ts
rest/v9/index.ts

* https://github.com/discord/discord-api-docs/pull/5723

feat(APIUser): add avatar decorations

---

deno/payloads/v10/application.ts
deno/payloads/v9/application.ts
deno/rest/v10/application.ts
deno/rest/v10/mod.ts
deno/rest/v9/application.ts
deno/rest/v9/mod.ts
payloads/v10/application.ts
payloads/v9/application.ts
rest/v10/application.ts
rest/v10/index.ts
rest/v9/application.ts
rest/v9/index.ts

- discord/discord-api-docs#5971

feat(APIApplication): approx guild count and get self application endpoint

---

deno/payloads/v10/guild.ts
deno/payloads/v9/guild.ts
deno/rest/common.ts
deno/rest/v10/guild.ts
deno/rest/v10/mod.ts
deno/rest/v9/guild.ts
deno/rest/v9/mod.ts
payloads/v10/guild.ts
payloads/v9/guild.ts
rest/common.ts
rest/v10/guild.ts
rest/v10/index.ts
rest/v9/guild.ts
rest/v9/index.ts

Split this up from #713 in the hopes of landing onboarding at some point this year
- discord/discord-api-docs#6101

feat: onboarding updates, mode field, and error codes

---

deno/gateway/v10.ts
deno/gateway/v9.ts
deno/payloads/v10/gateway.ts
deno/payloads/v9/gateway.ts
gateway/v10.ts
gateway/v9.ts
payloads/v10/gateway.ts
payloads/v9/gateway.ts

custom status for bots!
* https://github.com/discord/discord-api-docs/pull/6345

feat(GatewayActivityUpdateData): allow sending state

---

.github/CODEOWNERS
.github/auto_assign.yml
.github/workflows/pr-automation.yml
.prettierignore

chore: use code owners

---

deno/payloads/v10/auditLog.ts
deno/payloads/v9/auditLog.ts
payloads/v10/auditLog.ts
payloads/v9/auditLog.ts

- https://github.com/discord/discord-api-docs/pull/6367

feat(APIAuditLogOptions): add `integration_type`

---

deno/payloads/v10/teams.ts
deno/payloads/v9/teams.ts
payloads/v10/teams.ts
payloads/v9/teams.ts

- https://github.com/discord/discord-api-docs/pull/6384

refactor(TeamMemberRole): remove owner role

---

deno/payloads/v10/teams.ts
deno/payloads/v9/teams.ts
payloads/v10/teams.ts
payloads/v9/teams.ts

docs(APITeamMember): update deprecation message

---

deno/payloads/v10/user.ts
deno/payloads/v9/user.ts
payloads/v10/user.ts
payloads/v9/user.ts

- https://github.com/discord/discord-api-docs/pull/6394

feat(ConnectionService): support twitter rebrand update

---

deno/payloads/v10/auditLog.ts
deno/payloads/v10/guild.ts
deno/payloads/v9/auditLog.ts
deno/payloads/v9/guild.ts
deno/rest/v10/channel.ts
deno/rest/v9/channel.ts
payloads/v10/auditLog.ts
payloads/v10/guild.ts
payloads/v9/auditLog.ts
payloads/v9/guild.ts
rest/v10/channel.ts
rest/v9/channel.ts

This pull request fixes some of the TypeDoc typos that I and others found.

docs: fix TypeDoc typos

---

deno/rest/v10/channel.ts
deno/rest/v9/channel.ts
rest/v10/channel.ts
rest/v9/channel.ts

Fixes `RESTPostAPIGuildForumThreadsJSONBody`'s reference link.

docs(RESTPostAPIGuildForumThreadsJSONBody): Fix reference link

---

website/docusaurus.config.js

chore: change docusaurus branch name

---

deno/rest/v10/stageInstance.ts
deno/rest/v9/stageInstance.ts
rest/v10/stageInstance.ts
rest/v9/stageInstance.ts

- https://github.com/discord/discord-api-docs/pull/5687

feat(RESTPostAPIStageInstanceJSONBody): add `guild_scheduled_event_id`

---

deno/payloads/v10/application.ts
deno/payloads/v9/application.ts
deno/rest/v10/application.ts
deno/rest/v10/mod.ts
deno/rest/v9/application.ts
deno/rest/v9/mod.ts
payloads/v10/application.ts
payloads/v9/application.ts
rest/v10/application.ts
rest/v10/index.ts
rest/v9/application.ts
rest/v9/index.ts

- https://github.com/discord/discord-api-docs/pull/6297

feat: Application patch and new properties

---

deno/gateway/v10.ts
deno/gateway/v9.ts
deno/payloads/v10/_interactions/base.ts
deno/payloads/v10/_interactions/responses.ts
deno/payloads/v10/mod.ts
deno/payloads/v10/monetization.ts
deno/payloads/v9/_interactions/base.ts
deno/payloads/v9/_interactions/responses.ts
deno/payloads/v9/mod.ts
deno/payloads/v9/monetization.ts
deno/rest/v10/mod.ts
deno/rest/v10/monetization.ts
deno/rest/v9/mod.ts
deno/rest/v9/monetization.ts
gateway/v10.ts
gateway/v9.ts
payloads/v10/_interactions/base.ts
payloads/v10/_interactions/responses.ts
payloads/v10/index.ts
payloads/v10/monetization.ts
payloads/v9/_interactions/base.ts
payloads/v9/_interactions/responses.ts
payloads/v9/index.ts
payloads/v9/monetization.ts
rest/v10/index.ts
rest/v10/monetization.ts
rest/v9/index.ts
rest/v9/monetization.ts

Feel free to suggest changes
- https://github.com/discord/discord-api-docs/pull/6451
- https://github.com/discord/discord-api-docs/pull/6452
- https://github.com/discord/discord-api-docs/pull/6477/

feat: premium app subscriptions

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/6499

feat(RESTJSONErrorCodes): add `40074` and `50057`

---

deno/rest/v10/guild.ts
deno/rest/v9/guild.ts
rest/v10/guild.ts
rest/v9/guild.ts
tests/v10/onboarding.test-d.ts

- https://github.com/discord/discord-api-docs/pull/6479

fix(RESTPutAPIGuildOnboardingJSONBody): optional keys and flattened emoji

---

deno/rest/v10/webhook.ts
deno/rest/v9/webhook.ts
rest/v10/webhook.ts
rest/v9/webhook.ts

- https://github.com/discord/discord-api-docs/pull/6560

feat(RESTPostAPIWebhookWithTokenJSONBody): add `applied_tags`

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/6577

feat(Locale): add `SpanishLATAM`

---

.eslintplugin/tsconfig.json
tsconfig.json

chore: remove deprecated importsNotUsedAsValues from tsconfig

---

scripts/bump-version.mjs

Do not create new releases if the only commit author after the last release was Renovate bot.

ci: ignore new releases triggered only by renovate

---

scripts/bump-version.mjs

- https://github.com/discordjs/discord-api-types/pull/928#issuecomment-2017882752

ci: ignore commits by dependabot

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/6720

feat(RESTJSONErrorCodes): Add `500_000`

---

deno/rest/v10/mod.ts
deno/rest/v9/mod.ts
rest/v10/index.ts
rest/v9/index.ts

- https://github.com/discord/discord-api-docs/pull/6720

feat(Routes): Add `guildBulkBan()` route

---

deno/rest/v10/guild.ts
deno/rest/v9/guild.ts
rest/v10/guild.ts
rest/v9/guild.ts

- https://github.com/discord/discord-api-docs/pull/6720

feat(Guild): add `RESTPostAPIGuildBulkBan` result and json body

---

deno/rest/v10/user.ts
deno/rest/v9/user.ts
rest/v10/user.ts
rest/v9/user.ts

- https://github.com/discord/discord-api-docs/pull/6710

feat: bot banners

---

deno/payloads/v10/user.ts
deno/payloads/v9/user.ts
payloads/v10/user.ts
payloads/v9/user.ts

- https://github.com/discord/discord-api-docs/pull/6716

feat(ConnectionService): add bungie connection

---

deno/payloads/v10/auditLog.ts
deno/payloads/v9/auditLog.ts
payloads/v10/auditLog.ts
payloads/v9/auditLog.ts

I am, once again, splitting up the onboarding pull requests
- https://github.com/discord/discord-api-docs/pull/6041

feat(AuditLogEvent): onboarding events

---

deno/payloads/v10/user.ts
deno/payloads/v9/user.ts
payloads/v10/user.ts
payloads/v9/user.ts

- https://github.com/discord/discord-api-docs/pull/6395

feat(ConnectionService): add `domain`

---

deno/payloads/v10/monetization.ts
deno/payloads/v9/monetization.ts
deno/rest/v10/mod.ts
deno/rest/v10/monetization.ts
deno/rest/v9/mod.ts
deno/rest/v9/monetization.ts
payloads/v10/monetization.ts
payloads/v9/monetization.ts
rest/v10/index.ts
rest/v10/monetization.ts
rest/v9/index.ts
rest/v9/monetization.ts

- https://github.com/discord/discord-api-docs/pull/6820

feat: one time premium app purchases

---

deno/payloads/v10/guild.ts
deno/payloads/v10/user.ts
deno/payloads/v9/guild.ts
deno/payloads/v9/user.ts
deno/rest/v10/mod.ts
deno/rest/v9/mod.ts
payloads/v10/guild.ts
payloads/v10/user.ts
payloads/v9/guild.ts
payloads/v9/user.ts
rest/v10/index.ts
rest/v9/index.ts

- https://github.com/discord/discord-api-docs/pull/6464

feat: support avatar decorations

---

deno/rest/v10/channel.ts
deno/rest/v9/channel.ts
rest/v10/channel.ts
rest/v9/channel.ts

- https://github.com/discord/discord-api-docs/pull/6377

feat: add type query param for get reactions endpoint

---

deno/gateway/v10.ts
deno/gateway/v9.ts
gateway/v10.ts
gateway/v9.ts

- https://github.com/discord/discord-api-docs/pull/6375
- https://github.com/discord/discord-api-docs/pull/6873

feat: add gateway events payload for super reactions

---

deno/gateway/v9.ts
gateway/v9.ts

docs: reeeee

---

deno/payloads/v10/auditLog.ts
deno/payloads/v9/auditLog.ts
payloads/v10/auditLog.ts
payloads/v9/auditLog.ts

- https://github.com/discord/discord-api-docs/pull/6041

feat(AuditLogEvent): home settings events

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

- https://github.com/discord/discord-api-docs/pull/6558

feat(MessageType): add incident related types

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

- https://github.com/discord/discord-api-docs/pull/6945

feat(APIAttachment): add `title`

---

deno/payloads/v10/poll.ts
deno/payloads/v9/poll.ts
deno/rest/v10/poll.ts
deno/rest/v9/poll.ts
payloads/v10/poll.ts
payloads/v9/poll.ts
rest/v10/poll.ts
rest/v9/poll.ts

- https://github.com/discord/discord-api-docs/pull/6968

fix(RESTAPIPollCreate): optional properties

---

deno/rest/v10/user.ts
deno/rest/v9/user.ts
rest/v10/user.ts
rest/v9/user.ts

- https://github.com/discord/discord-api-docs/pull/6982

feat(RESTAPIPartialCurrentUserGuild): add `banner`

---

deno/payloads/v10/user.ts
deno/payloads/v9/user.ts
payloads/v10/user.ts
payloads/v9/user.ts

- https://github.com/discord/discord-api-docs/pull/6995

feat(ConnectionService): add `Roblox`

---

deno/payloads/v10/application.ts
deno/payloads/v9/application.ts
payloads/v10/application.ts
payloads/v9/application.ts

- https://github.com/discord/discord-api-docs/pull/7070

feat(APIApplication): `approximate_user_install_count`

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/7081

feat(RESTJSONErrorCodes): `UnknownStickerPack`

---

deno/payloads/v10/guildScheduledEvent.ts
deno/payloads/v9/guildScheduledEvent.ts
deno/rest/v10/guildScheduledEvent.ts
deno/rest/v9/guildScheduledEvent.ts
payloads/v10/guildScheduledEvent.ts
payloads/v9/guildScheduledEvent.ts
rest/v10/guildScheduledEvent.ts
rest/v9/guildScheduledEvent.ts

- https://github.com/discord/discord-api-docs/pull/7058

feat: recurring scheduled events

---

deno/payloads/v10/guildScheduledEvent.ts
deno/payloads/v9/guildScheduledEvent.ts
payloads/v10/guildScheduledEvent.ts
payloads/v9/guildScheduledEvent.ts

fix: interface name

---

deno/rest/v10/guildScheduledEvent.ts
deno/rest/v9/guildScheduledEvent.ts
rest/v10/guildScheduledEvent.ts
rest/v9/guildScheduledEvent.ts

- <https://github.com/discord/discord-api-docs/pull/7062>

fix: nullable `recurrence_rule` on patch

---

deno/payloads/v10/guild.ts
deno/payloads/v9/guild.ts
payloads/v10/guild.ts
payloads/v9/guild.ts

- https://github.com/discord/discord-api-docs/pull/7113

feat(GuildMemberFlags): `IsGuest` and `DmSettingsUpsellAcknowledged`

---

deno/payloads/v10/_interactions/applicationCommands.ts
deno/payloads/v10/application.ts
deno/payloads/v10/channel.ts
deno/payloads/v9/_interactions/applicationCommands.ts
deno/payloads/v9/application.ts
deno/payloads/v9/channel.ts
payloads/v10/_interactions/applicationCommands.ts
payloads/v10/application.ts
payloads/v10/channel.ts
payloads/v9/_interactions/applicationCommands.ts
payloads/v9/application.ts
payloads/v9/channel.ts

feat: remove unstable from stable fields

---

deno/payloads/v10/application.ts
deno/payloads/v9/application.ts
payloads/v10/application.ts
payloads/v9/application.ts

- https://github.com/discord/discord-api-docs/pull/7027

refactor(APIApplication): mark role_connections_verification_url and interactions_endpoint_url as nullable

---

deno/payloads/v10/user.ts
deno/payloads/v9/user.ts
payloads/v10/user.ts
payloads/v9/user.ts

- https://github.com/discord/discord-api-docs/pull/7095

feat(ConnectionService): add Amazon Music connection

---

deno/gateway/v10.ts
deno/gateway/v9.ts
deno/payloads/v10/monetization.ts
deno/payloads/v9/monetization.ts
deno/rest/v10/mod.ts
deno/rest/v10/monetization.ts
deno/rest/v9/mod.ts
deno/rest/v9/monetization.ts
gateway/v10.ts
gateway/v9.ts
payloads/v10/monetization.ts
payloads/v9/monetization.ts
rest/v10/index.ts
rest/v10/monetization.ts
rest/v9/index.ts
rest/v9/monetization.ts

- https://github.com/discord/discord-api-docs/pull/7109
- https://github.com/discord/discord-api-docs/pull/7110

feat: add subscriptions

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

- https://github.com/discord/discord-api-docs/pull/7116

feat(APIMessageSnapshotFields): add more fields

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

- https://github.com/discord/discord-api-docs/pull/6927
- https://github.com/discord/discord-api-docs/pull/7037
- https://github.com/discord/discord-api-docs/pull/7050

feat(MessageType): `PurchaseNotification` and `PollResult`

---

deno/rest/common.ts
rest/common.ts

- https://github.com/discord/discord-api-docs/pull/6959

feat(RESTJSONErrorCodes): add `40018`, `40019`, and `40094`

---

deno/gateway/v10.ts
deno/gateway/v9.ts
gateway/v10.ts
gateway/v9.ts

fix(GatewayGuildDeleteDispatchData): make `unavailable` optional

---

deno/gateway/v10.ts
deno/gateway/v9.ts
gateway/v10.ts
gateway/v9.ts

feat: missing subscription dispatch types

---

deno/payloads/v10/auditLog.ts
deno/payloads/v9/auditLog.ts
payloads/v10/auditLog.ts
payloads/v9/auditLog.ts

Includes the `recurrence_rule` key for the Audit Log Change object
- https://github.com/discord/discord-api-docs/pull/7058
Solves #1111

feat: recurrence rule change key on audit logs

---

deno/gateway/v10.ts
deno/gateway/v9.ts
deno/payloads/v10/guild.ts
deno/payloads/v9/guild.ts
deno/rest/common.ts
gateway/v10.ts
gateway/v9.ts
payloads/v10/guild.ts
payloads/v9/guild.ts
rest/common.ts

Adds missing soundboard types from #1113
- https://github.com/discord/discord-api-docs/pull/6260
- https://github.com/discord/discord-api-docs/pull/7207

fix: add missing soundboard types

---

deno/gateway/v10.ts
deno/gateway/v9.ts
deno/payloads/v10/guild.ts
deno/payloads/v9/guild.ts
gateway/v10.ts
gateway/v9.ts
payloads/v10/guild.ts
payloads/v9/guild.ts

- https://github.com/discord/discord-api-docs/pull/6986

feat: guild member banners

---

deno/payloads/v10/_interactions/base.ts
deno/payloads/v9/_interactions/base.ts
payloads/v10/_interactions/base.ts
payloads/v9/_interactions/base.ts

- https://github.com/discord/discord-api-docs/pull/7181

refactor: split interaction metadata objects

---

deno/payloads/v10/monetization.ts
deno/payloads/v9/monetization.ts
payloads/v10/monetization.ts
payloads/v9/monetization.ts

Resolves #1171
- https://github.com/discord/discord-api-docs/pull/7304

feat(APISubscription): add `renewal_sku_ids`

---

deno/payloads/v10/user.ts
deno/payloads/v9/user.ts
payloads/v10/user.ts
payloads/v9/user.ts

- https://github.com/discord/discord-api-docs/pull/7290

feat(ConnectionService): `Bluesky` and `Mastodon`

---

deno/payloads/v10/_interactions/_applicationCommands/entryPoint.ts
deno/payloads/v10/_interactions/applicationCommands.ts
deno/payloads/v10/_interactions/responses.ts
deno/payloads/v9/_interactions/_applicationCommands/entryPoint.ts
deno/payloads/v9/_interactions/applicationCommands.ts
deno/payloads/v9/_interactions/responses.ts
deno/rest/v10/interactions.ts
deno/rest/v9/interactions.ts
payloads/v10/_interactions/_applicationCommands/entryPoint.ts
payloads/v10/_interactions/applicationCommands.ts
payloads/v10/_interactions/responses.ts
payloads/v9/_interactions/_applicationCommands/entryPoint.ts
payloads/v9/_interactions/applicationCommands.ts
payloads/v9/_interactions/responses.ts
rest/v10/interactions.ts
rest/v9/interactions.ts

Implements missing payload from #1077 
- https://github.com/discord/discord-api-docs/pull/7106

feat(payloads): add entrypoint command payloads

---

deno/payloads/v10/guild.ts
deno/payloads/v9/guild.ts
deno/rest/v10/guild.ts
deno/rest/v10/mod.ts
deno/rest/v9/guild.ts
deno/rest/v9/mod.ts
payloads/v10/guild.ts
payloads/v9/guild.ts
rest/v10/guild.ts
rest/v10/index.ts
rest/v9/guild.ts
rest/v9/index.ts

- https://github.com/discord/discord-api-docs/pull/7360

feat(APIGuild): add `incidents_data`

---

deno/rest/v10/webhook.ts
deno/rest/v9/webhook.ts
rest/v10/webhook.ts
rest/v9/webhook.ts

- https://github.com/discord/discord-api-docs/pull/7368

feat(webhook): add `with_components` query param

---

deno/payloads/v10/_interactions/base.ts
deno/payloads/v9/_interactions/base.ts
payloads/v10/_interactions/base.ts
payloads/v9/_interactions/base.ts

- https://github.com/discord/discord-api-docs/pull/7451

feat(APIBaseInteraction): add `attachment_size_limit`

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
deno/rest/v10/channel.ts
deno/rest/v10/webhook.ts
deno/rest/v9/channel.ts
deno/rest/v9/webhook.ts
payloads/v10/channel.ts
payloads/v9/channel.ts
rest/v10/channel.ts
rest/v10/webhook.ts
rest/v9/channel.ts
rest/v9/webhook.ts

follow-up PR to #1190 with docs from the new components api docs https://github.com/discord/discord-api-docs/pull/7487

docs: components v2

---

deno/gateway/v9.ts
deno/rest/v9/soundboard.ts
gateway/v9.ts
rest/v9/soundboard.ts

Some imports were referencing other API versions.

fix: Import from respective version

---

deno/payloads/v10/channel.ts
deno/payloads/v9/auditLog.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/auditLog.ts
payloads/v9/channel.ts
tests/v10/channel.ts

fix: discriminated thread channel types

---

api-extractor.json
website/docusaurus.config.ts

An addition to #1257, adding voice v8 documentation to the website

chore(docs): add voice v8 to docs

---

deno/payloads/v10/webhook.ts
deno/payloads/v9/webhook.ts
payloads/v10/webhook.ts
payloads/v9/webhook.ts

- https://github.com/discord/discord-api-docs/pull/7599

refactor(webhook): Remove `@unstable` for application deauthorised

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
deno/voice/v4.ts
payloads/v10/channel.ts
payloads/v9/channel.ts
voice/v4.ts

https://github.com/discordjs/discord-api-types/actions/runs/15499419923/job/43643719889#step:15:31

docs: resolved api-extractor warnings

---

deno/payloads/v10/application.ts
deno/payloads/v9/application.ts
payloads/v10/application.ts
payloads/v9/application.ts

- https://github.com/discord/discord-api-docs/pull/7613

feat(APIApplication): add `approximate_user_authorization_count`

---

deno/payloads/v10/user.ts
deno/payloads/v9/user.ts
payloads/v10/user.ts
payloads/v9/user.ts

- https://github.com/discord/discord-api-docs/pull/7614

feat(APIUser): add `collectibles`

---

deno/payloads/v10/guild.ts
deno/payloads/v10/permissions.ts
deno/payloads/v9/guild.ts
deno/payloads/v9/permissions.ts
deno/rest/v10/guild.ts
deno/rest/v9/guild.ts
payloads/v10/guild.ts
payloads/v10/permissions.ts
payloads/v9/guild.ts
payloads/v9/permissions.ts
rest/v10/guild.ts
rest/v9/guild.ts

- https://github.com/discord/discord-api-docs/pull/7549

feat: role gradient colors

---

deno/payloads/v10/guild.ts
deno/payloads/v9/guild.ts
payloads/v10/guild.ts
payloads/v9/guild.ts

- https://github.com/discord/discord-api-docs/pull/7699

feat(GuildMemberFlags): Add `AUTOMOD_QUARANTINED_GUILD_TAG`

---

deno/payloads/v10/guild.ts
deno/payloads/v9/guild.ts
payloads/v10/guild.ts
payloads/v9/guild.ts

- https://github.com/discord/discord-api-docs/pull/7710

feat(GuildFeature): Add `GUILD_TAGS`

---

deno/payloads/v10/_interactions/modalSubmit.ts
deno/payloads/v10/_interactions/responses.ts
deno/payloads/v10/channel.ts
deno/payloads/v9/_interactions/modalSubmit.ts
deno/payloads/v9/_interactions/responses.ts
deno/payloads/v9/channel.ts
payloads/v10/_interactions/modalSubmit.ts
payloads/v10/_interactions/responses.ts
payloads/v10/channel.ts
payloads/v9/_interactions/modalSubmit.ts
payloads/v9/_interactions/responses.ts
payloads/v9/channel.ts

- https://canary.discord.com/channels/222078108977594368/1402934237358985246
- https://github.com/discord/discord-api-docs/pull/7804

feat: More label components and text display in modals

---

deno/gateway/v10.ts
deno/gateway/v9.ts
deno/payloads/v10/invite.ts
deno/payloads/v9/invite.ts
gateway/v10.ts
gateway/v9.ts
payloads/v10/invite.ts
payloads/v9/invite.ts

- https://github.com/discord/discord-api-docs/pull/7779

feat: Update invite types

---

deno/payloads/v10/guild.ts
deno/payloads/v9/guild.ts
deno/rest/v10/guild.ts
deno/rest/v9/guild.ts
payloads/v10/guild.ts
payloads/v9/guild.ts
rest/v10/guild.ts
rest/v9/guild.ts

fix: Add `RESTPutAPIGuildIncidentActionsResult`
