v6/payloads/channel.ts

APIMessage#mentions is an array of users, not just the user by itself - this PR reflects updates the typings to reflect such state.

fix(APIMessage): Correct APIMessage#mentions type

---

CHANGELOG.md
README.md
package-lock.json
package.json
v6/rest/oauth2.ts

You thought this module had long named exports? You didn't know what you signed up for! Introducing... `RESTPostOAuth2AccessTokenWithBotAndGuildsAndWebhookIncomingScopeResult`! And others, mind you...

feat: add oauth2 types

---

v6/payloads/user.ts

ref: https://discord.com/developers/docs/resources/user#user-object
premium_type is optional

fix(APIUser): premium_type is optional

---

v6/gateway/index.ts

ref: https://discord.com/developers/docs/topics/gateway#identify-identify-connection-properties
the `device` in `GatewayIdentifyProperties` should be `$device` not `device`

fix(GatewayIdentifyProperties): rename `device` to `$device`

---

v6/payloads/channel.ts

docs ref: https://discord.com/developers/docs/resources/channel#channel-object
position is only present on guild channels

fix(APIChannel): position is optional

---

v6/rest/guild.ts

on the API docs for [Create Guild (POST /guilds)](https://discord.com/developers/docs/resources/guild#create-guild) there are a couple of info boxes stating that roles and channels can have an integer ID as a placeholder, eg for creating channel overwrites, this PR corrects these types into numbers
This PR also corrects the type for `roles` in `RESTPostAPIGuildsJSONBody` as it was previously typed as `APIRole` which isn't technically correct; the API won't accept permissons_new here, 
`afk_channel_id` and `system_channel_id` are documented to be of type snowflake, but testing shows that the API accepts an integer, (there is an issue on the API about this https://github.com/discord/discord-api-docs/issues/2089)
also i think these types need better names perhaps? im really not good with …

fix(RESTPostAPIGuildsJSONBody): use correct types

---

package-lock.json
v8/gateway/index.ts

As per [documentation](https://discord.com/developers/docs/topics/gateway#heartbeat).
> The inner d key is the last sequence number—s—received by the client. If you have not yet received one, send null.

fix(GatewayHeartbeat): d is nullable

---

v8/gateway/index.ts

Currently, `GatewayIdentify` uses the `GatewayPresenceUpdate` interface, however that is used for presences that the client receives from Discord and `GatewayPresenceUpdateData` should be used.

fix(GatewayIdentify): use correct presence interface

---

package-lock.json
package.json

Because 0.6.1 had a very sort lifespan

chore: release 0.7.0

---

v8/gateway/index.ts
v8/payloads/gateway.ts

[API Docs](https://discord.com/developers/docs/topics/gateway#activity-object-activity-structure): Bots are only able to send `name`, `type`, and optionally `url`.
There is no separation between activity objects received from Discord and ones sent from the client. That causes problems like this, even though `created_at` should not be sent / will be ignored anyway.
I'm not fully familiar with the file structure yet, so if I placed it where it doesn't belong just let me know.

fix(GatewayPresence): correct type for sent activity objects

---

v8/gateway/index.ts

This PR syncs up with https://github.com/discord/discord-api-docs/commit/14460930d859237dc6cf8d464378b482d712fd6e (#2215 in the Discord API docs PRs), which was recently merged.

types(GatewayChannelPinsUpdateDispatch): make last_pin_timestamp nullable

---

v8/rest/guild.ts

As per [documentation](https://discord.com/developers/docs/resources/guild#modify-guild-json-params).
After testing them, it seems `null` casuses Discord to flip each of the said fields to their original defaults.

fix(RESTPatchAPIGuildJSONBody): multiple properties are actually nullable

---

v8/payloads/guild.ts

ref: https://github.com/discord/discord-api-docs/commit/2fe4e62a86f1d6b79bb57e3b46f0016b03391261

fix(APIGuildMember): drop nullability of `pending` prop

---

package-lock.json
package.json
v8/rest/guild.ts

<sup>i swear i literally didn't notice this was also broken with my last pr, please don't hurt me</sup>
All jokes aside, totally sorry you put out a version that didn't have this fixed as well, will try to pay more attention from here on out with those PRs, lol

chore: RESTPatchAPIGuildJSONBody `system_channel_flags` is optional; release 0.11.2

---

v8/payloads/auditLog.ts

An audit log change with the key `id` doesn't have the `new_value` property when a channel override is removed:
```jsonc
{
// ...
"action_type": 15, // CHANNEL_OVERWRITE_DELETE,
"changes": [
{"key": "id", "old_value": "<member/role id>"},
// ...
],
// ...
}
```
Can this get into #62?

fix(APIAuditLogChangeKeyID): make `new_value` optional

---

v8/payloads/auditLog.ts

The `type` property is only present in the channel overwrite changes and is therefore not always present.
Can this get into #62?

fix(APIAuditLogOptions): make `type` optional

---

v8/payloads/guild.ts

Syncs up with https://github.com/discord/discord-api-docs/commit/364e7fb3fbf4b304778afcd503fc8a4100a7987d

chore(APIGuildMember): make `premium_since` not optional

---

deno/v8/gateway/mod.ts
v8/gateway/index.ts

https://discord.com/developers/docs/topics/gateway#heartbeat
> This OP code is also bidirectional. The gateway may request a heartbeat from you in some situations, and you should send a heartbeat back to the gateway as you normally would.

chore(Gateway): clarify Heartbeat OP as bidirectional

---

v8/rest/guild.ts

This PR makes `afk_channel_id` and `system_channel_id` in `RESTPostAPIGuildsJSONBody` and `parent_id` in `APIGuildCreatePartialChannel` nullable.
These types are used in the following:
- `RESTPostAPIGuildsJSONBody`: I tested creating a guild using `POST /guilds` with a `null` `afk_channel_id` and `system_channel_id`, and a channel with a null `parent_id`, and it worked.
- `APITemplate` (via `APITemplateSerializedSourceGuild`): The [example template object in the docs](https://discord.com/developers/docs/resources/template#template-object-example-template-object) includes a `null` `afk_channel_id` and a null `parent_id` for a channel. I also tested creating a template from a guild without a system channel and the `system_channel_id` in the returned template object was `null`.
- …

fix(RESTPostAPIGuildsJSONBody): make some fields nullable

---

deno/common/mod.ts
deno/v8/gateway/mod.ts
deno/v8/payloads/auditLog.ts
deno/v8/payloads/channel.ts
deno/v8/payloads/gateway.ts
deno/v8/payloads/guild.ts
deno/v8/payloads/interactions.ts
deno/v8/payloads/invite.ts
deno/v8/payloads/oauth2.ts
deno/v8/payloads/teams.ts
deno/v8/payloads/user.ts
deno/v8/payloads/webhook.ts
deno/v8/rest/guild.ts
scripts/deno.mjs

AFAIA, Deno does not support `const enum` due to `--isolatedModules` being enabled https://github.com/denoland/deno/discussions/9082#discussioncomment-273198 (possible TypeScript bug)
I have added fixes although I want to be sure that this works. Any Deno reviewers would be extra appreciated.

fix(deno): replace `const enum` exports in deno with normal `enum`s

---

deno/v8/rest/channel.ts
v8/rest/channel.ts

Currently, `APIMessage` is not assignable to `RESTPostAPIChannelMessageJSONBody` due to the latter taking `tts?: true` as a property.
Also, just generally, setting `tts` to false *is* valid, but the typings don't allow for it.

fix(RESTPostAPIChannelMessageJSONBody): mark `tts` as a full boolean

---

.babelrc
.gitignore
.npmrc
CHANGELOG.md
README.md
deno/README.md
deno/shortcuts/v6.ts
deno/shortcuts/v8.ts
deno/v6.ts
deno/v8.ts
package-lock.json
package.json
scripts/deno.mjs
scripts/versions.mjs
shortcuts/v6.ts
shortcuts/v8.ts
tsconfig.eslint.json
tsconfig.json
v6.ts
v8.ts

While the node.js exports work perfectly fine, TypeScript doesn't parse those.
As such, TS users would get an error when importing the module.
Alongside that, this commit fixes eslint for mjs files,
which need @babel to process TLA
N/A

fix(TypeScript): imports not working in TypeScript

---

deno/rest/v8/mod.ts
rest/v8/index.ts

Adds documentation to GET route for webhook messages
BREAKING CHANGE: possibly a breaking change due to the fact that the `messageID` is now strictly typed as a Snowflake or `@me`
https://github.com/discord/discord-api-docs/issues/2410

docs(Routes): add GET route to `webhookMessage`

---

deno/payloads/v8/channel.ts
payloads/v8/channel.ts

https://discord.com/developers/docs/resources/guild#guild-object

fix(APIChannel): `rtc_region` is optional

---

deno/payloads/v8/invite.ts
payloads/v8/invite.ts

`APIInvite#channel` was marked as optional for some reason but it is not
https://discord.com/developers/docs/resources/invite

fix(APIInvite): `channel` is not optional

---

deno/payloads/v8/interactions.ts
payloads/v8/interactions.ts

This adds new interfaces for the guild members and channels returned when dealing with interactions. Previously, the extra properties were just added to the base interface, but that way it's harder to import and use them. (This will also be useful for discordjs/discord.js#5448)

feat: add new interfaces for interaction-related structures

---

deno/rest/v8/oauth2.ts
rest/v8/oauth2.ts

BREAKING CHANGE: `RESTGetAPIOauth2CurrentApplicationResult` and `RESTGetAPIOauth2CurrentAuthorizationResult` have been renamed to `RESTGetAPIOAuth2CurrentApplicationResult ` and `RESTGetAPIOAuth2CurrentAuthorizationResult`, to correct the casing of `OAuth`

fix(RESTOAuth2): correct casing of `OAuth`

---

deno/rest/common.ts
rest/common.ts

BREAKING CHANGE: This properly capitalizes certain error codes with the right OAuth capitalization
it's not an import fix. 

chore(RESTErrorCodes): correct casing for OAuth

---

deno/rest/v8/mod.ts
rest/v8/index.ts

This PR creates types for both array and object rest errors. [playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgJQFEBlAFUKimgB5CA+OAbwFgAoASGwgBNgAuOEgCuAWwBGaANxt2aKlADOAwtI4jgChZgDm-OAphRk21QF82bZKgw48ASSRI0FeUxldeAg0aQmZ6zR09b2MzC1YYAE8wPAB5IWsXaDgAXgJgLihuahDfABomOAB9OWglOAcnKCSoAG0AXThTOlU2AHoAKg62OA64AAsYGDAlNrbuBAVM7gA6LhFx4AA3YAAbCBjFcYhsBTaoYHQ0YCRcAGJSqABaAK1dBSvMSkxIq8uejra2UEhYOCiYgQSKQAILPSI1VJAsg1aj4DLQbK5bQFeHTajCcRoArxRKUaB0QmtVhcJAGOAgAREMhgqAvSFpFisOAsuAAIg8wDZAgArAAGPkAZh5eR6rLZlwU3LczNZcrZOBgCCWCCVGmlTLlWvFfI1Yu1BvZYFWmBg6GgIj1ssNNvZJXximltX1ttdmtdHvlnOlbIAQiDiIQiqQAJoABSDAGEABKxOyRkhs0XWz0etm3II+gBqmFWQjwIiE5IkcAgTlL6DgAAoAOS8BQAaxgGxrBRrmCQ3CoCG4rbgNYQEAUNYAlDM2 …

feat(RESTErrors): add types for rest errors

---

deno/rest/v8/channel.ts
deno/rest/v9/channel.ts
rest/v8/channel.ts
rest/v9/channel.ts

Adds the now supported embeds param to post / patch routes for standard messages, deprecates embed on v9.
https://github.com/discord/discord-api-docs/pull/3105

feat(Channel): add embeds to post / patch

---

deno/payloads/v8/guild.ts
deno/payloads/v9/guild.ts
payloads/v8/guild.ts
payloads/v9/guild.ts

This PR replaces the `nsfw` property of a guild payload with `nsfw_level`
[#2976](https://github.com/discord/discord-api-docs/pull/2976)

feat(APIGuild): add `nsfw_level`

---

deno/payloads/v8/auditLog.ts
deno/payloads/v9/auditLog.ts
payloads/v8/auditLog.ts
payloads/v9/auditLog.ts

This PR adds typings for stage instance related audit logs.
[#3060](https://github.com/discord/discord-api-docs/pull/3060)

feat: add stage instance related typings to audit logs

---

deno/utils/v8.ts
deno/utils/v9.ts
utils/v8.ts
utils/v9.ts

isStyledButton doesn't really describe what it does because all buttons have a style; isInteractionButton makes more sense because it says whether the button triggers an interaction when clicked

refactor: rename `isStyledButton` to `isInteractionButton`

---

deno/rest/v8/interactions.ts
deno/rest/v8/webhook.ts
deno/rest/v9/interactions.ts
deno/rest/v9/webhook.ts
rest/v8/interactions.ts
rest/v8/webhook.ts
rest/v9/interactions.ts
rest/v9/webhook.ts

other than Create Interaction Response, these are just aliases for the equivalent webhook routes, but not including them is inconsistent and can be confusing to the user
this also moves a Get Webhook Message type up so it isn't sandwiched between Edit Webhook Message types anymore

feat(Interactions): add interaction response and followup route

---

deno/payloads/v8/_interactions/slashCommands.ts
deno/payloads/v9/_interactions/slashCommands.ts
payloads/v8/_interactions/slashCommands.ts
payloads/v9/_interactions/slashCommands.ts

this lets you access resolved fields using ts 4.3.
this should be reverted once ts 4.4 releases ([august 24](https://github.com/microsoft/TypeScript/issues/44237))

fix: change resolved index types to string

---

deno/globals.ts
globals.ts

This reverts the `${bigint}` template type because it was hard to use for some developers

feat(Globals): revert template bigint type to string type

---

deno/payloads/v9/gateway.ts
payloads/v9/gateway.ts

Not sure when, but this finally got changed, oh and the members are full thread members now

fix(Gateway): thread list sync now sends an array as documented

---

deno/payloads/v8/_interactions/slashCommands.ts
deno/payloads/v9/_interactions/slashCommands.ts
payloads/v8/_interactions/slashCommands.ts
payloads/v9/_interactions/slashCommands.ts

BREAKING CHANGE: This renames `SubCommand` to `Subcommand`,
and `SubCommandGroup` to `SubcommandGroup`
Closes #170 

chore(ApplicationCommandOptionType): casing changes for subcommands

---

deno/payloads/v8/channel.ts
deno/payloads/v9/channel.ts
payloads/v8/channel.ts
payloads/v9/channel.ts

BREAKING CHANGE:
- `APIEmbedAuthor#name` is required, not optional
- `APIEmbedThumbnail#url` is required, not optional
- `APIEmbedImage#url` is required, not optional
https://github.com/discord/discord-api-docs/pull/3610

fix(Embed): corrent certain optional types as being required

---

deno/gateway/v8.ts
deno/gateway/v9.ts
gateway/v8.ts
gateway/v9.ts

BREAKING CHANGE: The three Application Command events have been removed
https://github.com/discord/discord-api-docs/pull/3691

chore(Gateway): remove `APPLICATION_COMMAND_*` events

---

deno/rest/v8/interactions.ts
deno/rest/v9/interactions.ts
rest/v8/interactions.ts
rest/v9/interactions.ts

As far as I can tell, the `version` field of APIApplicationCommands is not one that should be included in the POST data. So this omits it from `RESTPostAPIBaseApplicationCommandsJSONBody`.
#193, [discord/discord-api-docs#3524](https://github.com/discord/discord-api-docs/pull/3524)

fix(RESTPostAPIBaseApplicationCommandsJSONBody): omit `version` field

---

deno/payloads/v8/voice.ts
deno/payloads/v9/voice.ts
payloads/v8/voice.ts
payloads/v9/voice.ts

- https://github.com/discord/discord-api-docs/pull/3908

refactor(APIVoiceRegion): removed `vip` property

---

deno/rest/v8/channel.ts
deno/rest/v8/webhook.ts
deno/rest/v9/channel.ts
deno/rest/v9/webhook.ts
rest/v8/channel.ts
rest/v8/webhook.ts
rest/v9/channel.ts
rest/v9/webhook.ts

It seem like these types are doing this:
```ts
attachments: (object) & (object[])
```
instead of
```ts
attachments: (object & object)[]
```
[typescript playground link to demonstrate](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgQQAUBJfGGHACwFtgU4BvAKDlcQBMAuOAZximQBzANws26BABs6mWtz4CkIsa3bAe2AWBgIISAPzz+Q0WzjY9qFAH0YATzDBDvY0tNseCAF7BuSAK7UAEZo7qz+UJJGispmYFAQIHbWEVEuMWFwlMAIgpQwzgHBaHAAPnABkpKZAO4I7DCUhYEhUGUV-lWZwGDZtFCYks5BEBDSmEiiAL5MsxZIfHB1jRD+MISYUHQ83IQI2ADWADxEpORUtCgANHAA5GoaWjp6t+239bcAfHAAZHAbsAQgyOe0OJxIZAo2BodBgN1uEmkSFkwC+nwA2gBdOAAXjg6KYAEhmITCfVuLcAAy3K5EwkPTQIbS6JAU4jUTCCPAQdBwTDmNZ4SQIcjScyYGA0umImRyO4ygB0YCUtyJU1pxLp5LuAEYpaSGU8WRSAEr7A4JKpwQQIdD6wky5Fy27UOw29AK92qwkzTGiJjzRbLSgA7bcAAUoOOp0hF1h8MNTOeSFe5Xe7C+v3+mx0wKj4LOUJh13lUllqM+nwAlFjcfiiS …

fix: correct types for REST attachments

---

deno/payloads/v8/_interactions/_applicationCommands/chatInput.ts
deno/payloads/v9/_interactions/_applicationCommands/chatInput.ts
payloads/v8/_interactions/_applicationCommands/chatInput.ts
payloads/v9/_interactions/_applicationCommands/chatInput.ts

Subcommand options can be optional, 
example:
```ts
options: [
{
name: 'command',
description: 'The command you want to invoke.',
type: ApplicationCommandOptionType.SubcommandGroup,
options: [
{
name: 'spawnrandomcards',
description: 'Spawn lots of random cards.',
type: ApplicationCommandOptionType.Subcommand
}
]
}
],
```
and discord sends:
```js
[
{
"type": 2,
"options": [
{
"type": 1,
"name": "spawnrandomcards"
// types think that "options" is always here
}
],
"name": "command"
}
]
```
Not sure if this is even listed in the discord docs, but I deduced this just based off `console.log`'ing an interaction.

fix: make subcommand options optional

---

deno/rest/v8/guildScheduledEvent.ts
deno/rest/v9/guildScheduledEvent.ts
rest/v8/guildScheduledEvent.ts
rest/v9/guildScheduledEvent.ts

Currently importing this library in deno (1.16.3) on version 0.25.0 will cause this error:
```
error: Import 'https://deno.land/x/discord_api_types@0.25.0/payloads/v9.ts' failed, not found.
at https://deno.land/x/discord_api_types@0.25.0/rest/v9/guildScheduledEvent.ts:10:8
```
Here's my `import_map.json`:
```json
{
"imports": {
"discord_api_types": "https://deno.land/x/discord_api_types@0.25.0/v9.ts"
}
}
```
Reproduction: https://gitpod.io#snapshot/a6632653-7af6-4e60-bf9f-105616df115b
Run `curl -fsSL https://deno.land/x/install/install.sh | sudo DENO_INSTALL=/usr/local sh` to install Deno and run `deno run --import-map=import_map.json main.ts`

fix(deno): faulty import paths for guild scheduled events

---

deno/payloads/v8/channel.ts
deno/payloads/v9/channel.ts
payloads/v8/channel.ts
payloads/v9/channel.ts

close https://github.com/discordjs/discord-api-types/issues/247

fix(APISelectMenuComponent): `options` property is required

---

deno/gateway/v8.ts
deno/gateway/v9.ts
gateway/v8.ts
gateway/v9.ts

This PR does pretty much does the same thing as #258, except in a more elegant way. #258 would have made the field `t` and `s` always nullable, not just on non-dispatch payloads like this PR now does.
https://github.com/discord/discord-api-docs/blob/master/docs/topics/Gateway.md?plain=1#L28-L31

fix(NonDispatchPayload): `t` & `s` fields are always null on non-dispatch payloads

---

deno/rest/v8/channel.ts
deno/rest/v8/webhook.ts
deno/rest/v9/channel.ts
deno/rest/v9/webhook.ts
rest/v8/channel.ts
rest/v8/webhook.ts
rest/v9/channel.ts
rest/v9/webhook.ts

This PR changes the type of the `attachments` field of every message update body from a complete attachment object to only a partial object, with only the ID required.
It is currently impossible to send a query with all the information the typings are asking for, and sending fields like `filename` for already uploaded files results in an error from the API.
None

fix: only a partial object is needed when updating attachments

---

deno/gateway/v9.ts
gateway/v9.ts

Adds `GatewayStageInstanceCreateDispatch`, `GatewayStageInstanceDeleteDispatch`, and `GatewayStageInstanceUpdateDispatch` to `GatewayDispatchPayload` in `/gateway/v9`.
- [Discord API Reference](https://discord.com/developers/docs/topics/gateway#commands-and-events-gateway-events)
- Stage Instance dispatches are already [included in v8](https://github.com/discordjs/discord-api-types/blob/315ce3584917635b93a26123470f37a10bd8d846/gateway/v8.ts#L296-L298)

fix(GatewayStageInstance): Stage Instance dispatches not included in `GatewayDispatchPayload`

---

deno/payloads/v8/_interactions/_applicationCommands/chatInput.ts
deno/payloads/v9/_interactions/_applicationCommands/chatInput.ts
payloads/v8/_interactions/_applicationCommands/chatInput.ts
payloads/v9/_interactions/_applicationCommands/chatInput.ts
tests/v9/chatInputOptions.test-d.ts

The previous way that autocomplete was enforced create types that were hard/near impossible to use. This PR sacrifices the type strength for usability making it waaay easier to adopt. So essentially `choices` and `autocomplete` are no longer mutually exclusive.

types: make application command option union easier to use

---

deno/payloads/v8/guildScheduledEvent.ts
deno/payloads/v9/guildScheduledEvent.ts
payloads/v8/guildScheduledEvent.ts
payloads/v9/guildScheduledEvent.ts

This PR turns `APIGuildScheduledEvent` into a union of `APIStageInstanceGuildScheduledEvent`, `APIVoiceGuildScheduledEvent`, and `APIExternalGuildScheduledEvent`, which each has more precise types according to the docs.
This PR also fixes a bug as previously `APIGuildScheduledEvent#entity_metadata` was not nullable, even though it should be.
- https://discord.com/developers/docs/resources/guild-scheduled-event#guild-scheduled-event-object-field-requirements-by-entity-type
---
Technically, `entity_metadata` isn’t always `null` for stage instance events (see https://github.com/discord/discord-api-docs/issues/4198) and contains a `speaker_ids` field, but that [isn’t …

feat(APIGuildScheduledEvent): add more precise types for stage instance/voice/external events

---

deno/payloads/v8/auditLog.ts
deno/payloads/v9/auditLog.ts
payloads/v8/auditLog.ts
payloads/v9/auditLog.ts

Adds `communication_disabled_until` to the audit logs.
N/A

feat(APIAuditLogChangeData): Add `communication_disabled_until`

---

CHANGELOG.md
deno/CHANGELOG.md
package-lock.json
package.json

- **APIApplicationCommandOption:** correct type for integer and number ([#284](https://github.com/discordjs/discord-api-types/issues/284)) ([fe1f531](https://github.com/discordjs/discord-api-types/commit/fe1f5313a8fc13d0a2433738cce9be37f5d9eeb5))
- **APIAuditLogChangeData:** Add `communication_disabled_until` ([#281](https://github.com/discordjs/discord-api-types/issues/281)) ([0cf51ab](https://github.com/discordjs/discord-api-types/commit/0cf51abc267bd6246a7952e7f6a23fa8c5db290a))
- **APIGuildScheduledEvent:** add more precise types for stage instance/voice/external events ([#278](https://github.com/discordjs/discord-api-types/issues/278)) ([751aee6](https://github.com/discordjs/discord-api-types/commit/751aee6fa7d …

chore(release): 0.26.1 🎉

---

deno/rest/v8/guild.ts
deno/rest/v9/guild.ts
rest/v8/guild.ts
rest/v9/guild.ts

**Please describe the changes this PR makes and why it should be merged:** `communication_disabled_until `is an accepted field in the "Modify Guild Member" JSON body. This is a minor change that updates the corresponding type in API v8 and v9 to reflect that.
discord/discord-api-docs#4075
This is a revised version of #288.

feat(RESTPatchAPIGuildMember): add `communication_disabled_until` field

---

deno/payloads/v8/_interactions/base.ts
deno/payloads/v8/_interactions/ping.ts
deno/payloads/v9/_interactions/base.ts
deno/payloads/v9/_interactions/ping.ts
payloads/v8/_interactions/base.ts
payloads/v8/_interactions/ping.ts
payloads/v9/_interactions/base.ts
payloads/v9/_interactions/ping.ts

Note: `locale` is being set to required on `APIBaseInteraction` simply because it's `Omit`'ed from the Ping interaction. Ping is the only case where `locale` isn't present.
- https://github.com/discord/discord-api-docs/pull/4265

feat(APIInteraction): add locale props to interactions

---

deno/payloads/v8/_interactions/base.ts
deno/payloads/v9/_interactions/base.ts
deno/rest/common.ts
payloads/v8/_interactions/base.ts
payloads/v9/_interactions/base.ts
rest/common.ts

Who doesn't like autocompleted strings?

feat(Locales): add locale string enum

---

deno/payloads/v8/gateway.ts
deno/payloads/v9/gateway.ts
payloads/v8/gateway.ts
payloads/v9/gateway.ts

This PR changes the "Game" activity type to "Playing" to match with the Discord API docs name (https://discord.com/developers/docs/game-sdk/activities#data-models-activitytype-enum) and to be in line with the old discord.js name for the same type

refactor(ActivityType): change `Game` to `Playing`

---

deno/payloads/v8/_interactions/base.ts
deno/payloads/v9/_interactions/base.ts
payloads/v8/_interactions/base.ts
payloads/v9/_interactions/base.ts

- https://github.com/discord/discord-api-docs/pull/4354

feat(APIMessageInteraction): add `member` field

---

deno/payloads/v9/channel.ts
payloads/v9/channel.ts

* https://github.com/discord/discord-api-docs/pull/4282

feat(MessageFlags): add `FailedToMentionSomeRolesInThread`

---

deno/rest/v8/channel.ts
deno/rest/v9/channel.ts
rest/v8/channel.ts
rest/v9/channel.ts

- https://github.com/discord/discord-api-docs/pull/4405

refactor: allow omitting `allow` and `deny` in `permission_overwrites`

---

deno/gateway/v9.ts
gateway/v9.ts

- https://github.com/discord/discord-api-docs/commit/1875d80011ea62bf555ce807459ccf97950291e9

feat(GatewayThreadCreateDispatch): Add `newly_created` field`

---

deno/gateway/v9.ts
gateway/v9.ts

fix(GatewayThreadCreateDispatchData): `newly_created` is optional, and `true` when present

---

deno/payloads/v8/guildScheduledEvent.ts
deno/payloads/v9/guildScheduledEvent.ts
payloads/v8/guildScheduledEvent.ts
payloads/v9/guildScheduledEvent.ts

- https://github.com/discord/discord-api-docs/pull/4454

refactor(APIGuildScheduledEventBase): make `creator_id` optional

---

deno/payloads/v8/_interactions/autocomplete.ts
deno/payloads/v8/interactions.ts
deno/payloads/v9/_interactions/autocomplete.ts
deno/payloads/v9/interactions.ts
payloads/v8/_interactions/autocomplete.ts
payloads/v8/interactions.ts
payloads/v9/_interactions/autocomplete.ts
payloads/v9/interactions.ts
tests/v9/interactions.test-d.ts

As I understand it, the `data` property cannot be missing in any of the current interaction types (except for ping) ([source](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-structure))
As per @vladfrangu's request (https://github.com/discordjs/discord-api-types/pull/321#issuecomment-1036494951), added separate dm/guild types of the `APIApplicationCommandAutocompleteInteraction`

fix: make `data` required in autocomplete interaction and add separate dm/guild types

---

deno/payloads/v8/interactions.ts
deno/payloads/v9/interactions.ts
payloads/v8/interactions.ts
payloads/v9/interactions.ts

- Export autocomplete API interaction
- Every other API interaction is exported, why not autocomplete?
- This will allow people (like me) to use the autocomplete type specifically and not a generic interaction
- None

fix(APIInteractions): export ApplicationCommandAutocomplete

---

deno/payloads/v8/_interactions/modalSubmit.ts
deno/payloads/v8/_interactions/responses.ts
deno/payloads/v8/channel.ts
deno/payloads/v9/_interactions/modalSubmit.ts
deno/payloads/v9/_interactions/responses.ts
deno/payloads/v9/channel.ts
deno/rest/v8/channel.ts
deno/rest/v8/webhook.ts
deno/rest/v9/channel.ts
deno/rest/v9/webhook.ts
payloads/v8/_interactions/modalSubmit.ts
payloads/v8/_interactions/responses.ts
payloads/v8/channel.ts
payloads/v9/_interactions/modalSubmit.ts
payloads/v9/_interactions/responses.ts
payloads/v9/channel.ts
rest/v8/channel.ts
rest/v8/webhook.ts
rest/v9/channel.ts
rest/v9/webhook.ts

Doing `Exclude` within the `APIActionRow` caused a lot of type issues. So now `APIActionRow<T>` only accepts generic types that aren't action rows themselves. (Which is more intuitive IMO)

refactor(APIComponents): simplify action row types

---

scripts/bump-version.mjs

fix(CI): skip pull request checks for runs that don't include the token

---

deno/payloads/v8/_interactions/autocomplete.ts
deno/payloads/v9/_interactions/autocomplete.ts
payloads/v8/_interactions/autocomplete.ts
payloads/v9/_interactions/autocomplete.ts
tests/v9/interactions.test-d.ts

- Makes the `options` field required for autocomplete interactions
- Even though it is technically "optional" in the docs, in practice it will always be there when receiving an interaction
- The whole point of an autocomplete interaction is that a user is typing out an option. Therefore autocomplete interaction cannot be sent without options.
- [Interaction Object Data Structure](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-data-structure)

fix(APIApplicationCommandAutocompleteInteraction): make `options` field required

---

deno/payloads/v10/_interactions/autocomplete.ts
payloads/v10/_interactions/autocomplete.ts

- Same changes as #332 but for v10 (since that PR was merged before 332)
- [Interaction Object Data Structure](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-data-structure)

fix(APIApplicationCommandAutocompleteInteraction): make `options` field required for v10 (PR #332 redo)

---

.github/workflows/create-pr-for-release-and-publish.yml

@vladfrangu asked me to make this PR in Discord DMs
N.A.
Sidenote that you should manually un-deprecate 0.26.1 after merging this @vladfrangu `npm deprecate discord-api-types@0.26.1 ""`
> To un-deprecate a package, specify an empty string (`""`) for the message argument. Note that you must use double quotes with no space between them to format an empty string.

ci: remove deprecate regular versions

---

deno/payloads/v10/_interactions/messageComponents.ts
deno/payloads/v9/_interactions/messageComponents.ts
payloads/v10/_interactions/messageComponents.ts
payloads/v9/_interactions/messageComponents.ts

I have no idea if this is right or not lol, but I _think_ it is.
This adds types for specific Message Component Interactions. This is useful for when you know what type of component is sending an interaction
Vlad influenced me by asking me to export these

feat(MessageComponentInteraction): export specific interaction aliases

---

deno/utils/v10.ts
deno/utils/v9.ts
utils/v10.ts
utils/v9.ts

These functions are super useful for narrowing the type from the generic Interaction types into a specific interaction type

feat(Utils): add more typeguard functions to determine the interaction types

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

This exports the APIButtonComponentBase interface. This is necessary for libraries or other projects that are defining abstracted button logic that is then extended into custom id or link buttons. 
You can see a [concrete usage of this type here](https://github.com/IanMitchell/interaction-kit/pull/108/commits/1d8437b260d2be6412185b6dacbaf7c3835d7feb).

chore: export APIButtonComponentBase<T> interface

---

deno/payloads/v10/guildScheduledEvent.ts
deno/payloads/v9/guildScheduledEvent.ts
payloads/v10/guildScheduledEvent.ts
payloads/v9/guildScheduledEvent.ts

- https://github.com/discord/discord-api-docs/pull/4608

refactor(APIGuildScheduledEventBase): make `description` nullable

---

.gitignore

The correct capitalization used by macOS is `.DS_Store`
`.DS_Store` is a file used exclusively by macOS for meta data and other custom attributes.[^1] While this file may be useful for macOS, it does not have any value nor usefulness in the code base. Therefore, this PR should be merged in order to properly prevent contributors using macOS from accidentally committing this file.
[^1]: https://en.wikipedia.org/wiki/.DS_Store

Fix(.gitignore): Capitalization error

---

deno/payloads/v10/guild.ts
deno/payloads/v9/guild.ts
payloads/v10/guild.ts
payloads/v9/guild.ts

The type of an integration was exported as `APIGuildInteractionType`, but this is misnamed. It should be `APIGuildIntegrationType`. It's not an interaction.

fix(APIGuildIntegrationType): correct name of type

---

deno/payloads/common.ts
deno/payloads/v10/_interactions/_applicationCommands/_chatInput/base.ts
deno/payloads/v10/_interactions/_applicationCommands/_chatInput/shared.ts
deno/payloads/v10/_interactions/applicationCommands.ts
deno/payloads/v9/_interactions/_applicationCommands/_chatInput/base.ts
deno/payloads/v9/_interactions/_applicationCommands/_chatInput/shared.ts
deno/payloads/v9/_interactions/applicationCommands.ts
payloads/common.ts
payloads/v10/_interactions/_applicationCommands/_chatInput/base.ts
payloads/v10/_interactions/_applicationCommands/_chatInput/shared.ts
payloads/v10/_interactions/applicationCommands.ts
payloads/v9/_interactions/_applicationCommands/_chatInput/base.ts
payloads/v9/_interactions/_applicationCommands/_chatInput/shared.ts
payloads/v9/_interactions/applicationCommands.ts

- https://github.com/discord/discord-api-docs/pull/4653

feat(APIApplicationCommand): add command localization

---

deno/payloads/v10/auditLog.ts
deno/payloads/v9/auditLog.ts
payloads/v10/auditLog.ts
payloads/v9/auditLog.ts

Adds `image_hash`.
- https://github.com/discord/discord-api-docs/pull/4707

feat(APIAuditLogChange): add `APIAuditLogChangeKeyImageHash`

---

deno/payloads/v10/guild.ts
deno/payloads/v9/guild.ts
deno/rest/v10/guild.ts
deno/rest/v9/guild.ts
payloads/v10/guild.ts
payloads/v9/guild.ts
rest/v10/guild.ts
rest/v9/guild.ts

- https://github.com/discord/discord-api-docs/pull/3469

docs(APIGuild): any guild can have `description`

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

- https://github.com/discord/discord-api-docs/pull/4571

refactor(APIGroupDMChannel): make `name` nullable

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
deno/rest/v10/channel.ts
deno/rest/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts
rest/v10/channel.ts
rest/v9/channel.ts

- https://github.com/discord/discord-api-docs/pull/4635

refactor: remove store channels

---

deno/globals.ts
globals.ts

Marks `UserWithNickname` and `UserWithOptionalNickname` as deprecated.
- https://github.com/discord/discord-api-docs/commit/a8f7638e79391bb70e15996d1d88488a3b6364b2
- https://github.com/discord/discord-api-docs/commit/e3921e168aa167503ae193439abe70106b58d914

docs(FormattingPatterns): mark `UserWithNickname` and `UserWithOptionalNickname` as deprecated

---

deno/rest/v10/guild.ts
deno/rest/v9/guild.ts
deno/utils/internals.ts
rest/v10/guild.ts
rest/v9/guild.ts
utils/internals.ts

This PR also fixes a bug where `RESTPostAPIGuildChannelJSONBody` would resolve to `never` since `Pick` and `Omit` don't consider disjoint props.
- https://github.com/discord/discord-api-docs/pull/4767

feat(RESTPostAPIGuildChannelJSONBody): add `default_auto_archive_duration` prop

---

deno/rest/v10/guild.ts
deno/rest/v9/guild.ts
rest/v10/guild.ts
rest/v9/guild.ts

https://discord.com/channels/222078108977594368/941291502372552735/967583651535667250
This allows supplying a `position` property to the create channel options type (`RESTPostAPIGuildChannelJSONBody`).
https://discord.com/developers/docs/resources/guild#create-guild-channel-json-params

fix: add `position` property to create channel options

---

deno/payloads/v10/oauth2.ts
deno/payloads/v9/oauth2.ts
payloads/v10/oauth2.ts
payloads/v9/oauth2.ts

Adds `DMChannelsRead` and `Voice` scopes to `OAuth2Scopes`.
- https://github.com/discord/discord-api-docs/pull/4917

feat(OAuth2Scopes): add new OAuth2 scopes

---

deno/payloads/v10/guild.ts
deno/payloads/v9/guild.ts
payloads/v10/guild.ts
payloads/v9/guild.ts

- https://github.com/discord/discord-api-docs/pull/4825

refactor(GuildFeature): thread archive durations are no longer boost locked

---

deno/gateway/v10.ts
deno/gateway/v9.ts
deno/payloads/v10/_interactions/_applicationCommands/permissions.ts
deno/payloads/v10/_interactions/applicationCommands.ts
deno/payloads/v10/auditLog.ts
deno/payloads/v10/oauth2.ts
deno/payloads/v9/_interactions/_applicationCommands/permissions.ts
deno/payloads/v9/_interactions/applicationCommands.ts
deno/payloads/v9/auditLog.ts
deno/payloads/v9/oauth2.ts
deno/rest/v10/guild.ts
deno/rest/v10/interactions.ts
deno/rest/v9/guild.ts
deno/rest/v9/interactions.ts
gateway/v10.ts
gateway/v9.ts
payloads/v10/_interactions/_applicationCommands/permissions.ts
payloads/v10/_interactions/applicationCommands.ts
payloads/v10/auditLog.ts
payloads/v10/oauth2.ts
payloads/v9/_interactions/_applicationCommands/permissions.ts
payloads/v9/_interactions/applicationCommands.ts
payloads/v9/auditLog.ts
payloads/v9/oauth2.ts
rest/v10/guild.ts
rest/v10/interactions.ts
rest/v9/guild.ts
rest/v9/interactions.ts

Credit to @vitorlops for making the basis for this PR.
- https://github.com/discord/discord-api-docs/pull/4830
- https://github.com/discord/discord-api-docs/pull/4836
- https://github.com/discord/discord-api-docs/pull/4833
- https://github.com/discord/discord-api-docs/pull/4845
- https://github.com/discord/discord-api-docs/pull/4861

feat: add support for application command permissions v2

---

deno/gateway/v10.ts
deno/gateway/v9.ts
deno/payloads/v10/guild.ts
deno/payloads/v9/guild.ts
gateway/v10.ts
gateway/v9.ts
payloads/v10/guild.ts
payloads/v9/guild.ts

Separete `GUILD_CREATE` event fields from `APIGuild` object. Please let me know if something is wrong, it's a bit confusing to me. 
- https://github.com/discord/discord-api-docs/pull/4888

refactor: separate `GUILD_CREATE` fields from `APIGuild` object

---

deno/rest/v10/guild.ts
deno/rest/v9/guild.ts
rest/v10/guild.ts
rest/v9/guild.ts

It adds endpoint types that I noticed were missing from the guilds file.

feat(rest): add missing guild routes results

---

deno/payloads/v10/_interactions/applicationCommands.ts
deno/payloads/v9/_interactions/applicationCommands.ts
payloads/v10/_interactions/applicationCommands.ts
payloads/v9/_interactions/applicationCommands.ts

- discord/discord-api-docs#4991

fix(APIApplicationCommand): `dm_permission` is not nullable and `default_member_permissions` is required

---

website/src/css/custom.scss

Fixes *all* link colors accidentally being overridden instead of just navbar link colors. 😅 
Before:
After:

fix: website link colors

---

deno/rest/v10/interactions.ts
deno/rest/v9/interactions.ts
rest/v10/interactions.ts
rest/v9/interactions.ts

Makes the post json `default_member permissions` optional.

fix(RestPostAPIBaseApplicationJSONBody): make `default_member_permissions` optional

---

deno/rest/v10/webhook.ts
deno/rest/v9/webhook.ts
rest/v10/webhook.ts
rest/v9/webhook.ts

- https://github.com/discord/discord-api-docs/pull/5007

feat(RESTPostAPIWebhookWithTokenJSONBody): add `thread_name`

---

deno/rest/v10/webhook.ts
deno/rest/v9/webhook.ts
rest/v10/webhook.ts
rest/v9/webhook.ts

`thread_name` should be optional, not required.

fix(Webhook): `thread_name` should be optional

---

deno/rest/v10/channel.ts
deno/rest/v9/channel.ts
rest/v10/channel.ts
rest/v9/channel.ts

- https://github.com/discord/discord-api-docs/pull/5013

docs(RESTPatchAPIChannelJSONBody): voice channels can be set as nsfw

---

deno/gateway/v10.ts
deno/gateway/v9.ts
gateway/v10.ts
gateway/v9.ts

- ~~discord/discord-api-docs#5058~~ https://github.com/discord/discord-api-docs/pull/5067

refactor(GatewayIdentifyProperties): remove `$` prefix from keys

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

Adds missing `proxy_url` property to `APIEmbedVideo`. 
https://discord.com/developers/docs/resources/channel#embed-object-embed-video-structure

feat(APIEmbedVideo): add missing `proxy_url` property

---

deno/payloads/v10/user.ts
deno/payloads/v8/user.ts
deno/payloads/v9/user.ts
payloads/v10/user.ts
payloads/v8/user.ts
payloads/v9/user.ts

Adds `@unstable` to the `Spammer` user flag.
This idea comes from #495, which adds `Quarantined` user flag. Both of them are not documented by Discord.

chore(UserFlags): add `@unstable` to `Spammer` flag

---

deno/rest/v10/mod.ts
deno/rest/v9/mod.ts
rest/v10/index.ts
rest/v9/index.ts

Adds the constant `CDNRoutes`, that contains each CDN entpoint from [DDevs Portal](https://discord.com/developers/docs/reference#image-formatting-cdn-endpoints). Made it because of https://github.com/discordjs/discord-api-types/pull/453#issuecomment-1139164200. With this, many other things are being added: `ImageFormats`, `CDNQuery` and `*Format` types.

feat(REST): add `CDNRoutes`

---

deno/payloads/v10/_interactions/_applicationCommands/_chatInput/string.ts
deno/payloads/v9/_interactions/_applicationCommands/_chatInput/string.ts
payloads/v10/_interactions/_applicationCommands/_chatInput/string.ts
payloads/v9/_interactions/_applicationCommands/_chatInput/string.ts

Adds `min_length` and `max_length` fields to `APIApplicationCommandStringOption`. 
Closes #512.
- https://github.com/discord/discord-api-docs/pull/5143

feat(APIApplicationCommandStringOption): add `min_length` and `max_length`

---

deno/payloads/v10/_interactions/_applicationCommands/_chatInput/integer.ts
deno/payloads/v10/_interactions/_applicationCommands/_chatInput/number.ts
deno/payloads/v8/_interactions/_applicationCommands/_chatInput/integer.ts
deno/payloads/v8/_interactions/_applicationCommands/_chatInput/number.ts
deno/payloads/v9/_interactions/_applicationCommands/_chatInput/integer.ts
deno/payloads/v9/_interactions/_applicationCommands/_chatInput/number.ts
payloads/v10/_interactions/_applicationCommands/_chatInput/integer.ts
payloads/v10/_interactions/_applicationCommands/_chatInput/number.ts
payloads/v8/_interactions/_applicationCommands/_chatInput/integer.ts
payloads/v8/_interactions/_applicationCommands/_chatInput/number.ts
payloads/v9/_interactions/_applicationCommands/_chatInput/integer.ts
payloads/v9/_interactions/_applicationCommands/_chatInput/number.ts

Fixes a typo on `Number` and `Integer` application command options, in the `max_value` field description (repeated word).

docs(APIApplicationCommandOption): number and integer typos in `max_value` field description

---

website/docs/Contributing.mdx

technically not `#discord-api-types` anymore :mmlol:

docs: update discord channel name

---

deno/rest/v10/interactions.ts
deno/rest/v9/interactions.ts
rest/v10/interactions.ts
rest/v9/interactions.ts

Adds mssing optional `id` property into `RESTPutAPIApplicationGuildCommandsJSONBody`.
- https://github.com/discord/discord-api-docs/pull/5171

feat(RESTPutAPIApplicationGuildCommandsJSONBody): add missing `id`

---

deno/gateway/v10.ts
deno/gateway/v9.ts
deno/payloads/v10/guild.ts
deno/payloads/v9/guild.ts
gateway/v10.ts
gateway/v9.ts
payloads/v10/guild.ts
payloads/v9/guild.ts

Adds missing `unavailable` field to `GatewayGuildCreateDispatchData`, forget in https://github.com/discordjs/discord-api-types/commit/17f5caa671da50a79d61393f5a970ce59c5d875e commit
- https://github.com/discord/discord-api-docs/pull/5124

feat(GatewayGuildCreateDispatchData): add missing `unavailable`

---

deno/payloads/v10/guild.ts
deno/payloads/v9/guild.ts
payloads/v10/guild.ts
payloads/v9/guild.ts

- https://github.com/discord/discord-api-docs/pull/5180

refactor(GuildFeature): remove `Commerce`

---

deno/rest/common.ts
rest/common.ts

Changes the name of the error code 30033, which is `MaximumThreadParticipants`, to `MaximumThreadParticipantsReached`.
This is to have more coherence according to the error message: "Max number of thread participants has been reached (1000)". 

refactor(RESTJSONErrorCodes): use `MaximumThreadParticipantsReached` instead in error code 30033

---

deno/gateway/v10.ts
deno/gateway/v9.ts
gateway/v10.ts
gateway/v9.ts

…perties mandatory
properties are listed as required on the documentation: https://discord.com/developers/docs/topics/gateway#guild-members-chunk
and seem to be regardless of nonce
```
2022-08-09 14:54:18.513  INFO  [src/shard/guild-member-handler.ts:58] sending guild member request 
{
guild_id: '917075127139717200',
query: 'a',
limit: 1
}
2022-08-09 14:54:18.650  INFO  [src/shard/guild-member-handler.ts:25] received chunk 
{
members: [
{
// ...
}
],
guild_id: '917075127139717200',
chunk_index: 0,
chunk_count: 1
}
2022-08-09 14:54:33.672  INFO  [src/shard/guild-member-handler.ts:58] sending guild member request 
{
guild_id: '917075127139717200',
query: 'a',
limit: 1,
nonce: '_a'
}
2022-08-09 14:54:33.819  INFO  [src/shard/guild-member-handler.ts:25] received chunk 
{
nonce: '_a',
members: …
```

fix(GatewayGuildMembersChunkDispatchData): make chunk pagination properties mandatory

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

Adds the missing properties to `APIVoiceChannel` (`last_message_id` and `rate_limit_per_user`) which were now included in the voice channel payload, with the "Text In Voice" feature, making it a text-based channel.
But to make it more dynamic takes `APIVoiceChannel` as a _base_ with the common properties in the voice channel types (Now it will be `APIVoiceChannelBase`) because a guild contains two types of voice channels: `GUILD_VOICE` and `GUILD_STAGE_VOICE`. 
So, this PR:
- Creates a type called **`APIGuildStageVoiceChannel`**, which covers the channel with the `GUILD_STAGE_VOICE` type.
- Adds `rate_limit_per_user` property to `APITextBasedChannel` (it already had the `last_message_id` property).
- Creates an …

feat(APIVoiceChannel): support text in voice, properties `last_message_id` and `rate_limit_per_user`

---

deno/rest/v10/channel.ts
rest/v10/channel.ts

Adds `has_more` missing field to `RESTGetAPIChannelUsersThreadsArchivedResult`.
In an older PR, the property `has_more` was deleted in `APIThreadList`, which is the value of this route type.
According to [`GET /channels/{channel.id}/users/@me/threads/archived/private`](https://discord.com/developers/docs/resources/channel#list-joined-private-archived-threads), the response body has the `has_more` field.

fix(RESTGetAPIChannelUsersThreadsArchivedResult): add `has_more` missing field

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

Adds notes about the `MESSAGE_CONTENT` intent, which will be [privileged for verified apps after August 31, 2022](https://support-dev.discord.com/hc/en-us/articles/4404772028055).
There are affected fields in `APIMessage`, which are `content`, `embeds`, `attachments`, and `components`.

docs: add notes about `MESSAGE_CONTENT` intent in affected data fields

---

deno/payloads/v10/_interactions/_applicationCommands/chatInput.ts
deno/payloads/v9/_interactions/_applicationCommands/chatInput.ts
payloads/v10/_interactions/_applicationCommands/chatInput.ts
payloads/v9/_interactions/_applicationCommands/chatInput.ts

Allows for importing helpful types like `APIApplicationCommandOptionBase` (less helpful for applications, very helpful for libraries)
N/A

feat(ApplicationCommand): export base chat input types

---

deno/payloads/common.ts
payloads/common.ts

Adds common JSON error types from discordjs/rest. Should be merged because there's currently no error types.
https://github.com/discordjs/discord.js/blob/e475b63f257f6261d73cb89fee9ecbcdd84e2a6b/packages/rest/src/lib/errors/DiscordAPIError.ts#L3-L18
https://discord.com/developers/docs/topics/opcodes-and-status-codes#json

feat: add common JSON error types

---

deno/globals.ts
globals.ts

Adds `ApplicationCommand` format to `FormattingPatterns` constant.
- https://github.com/discord/discord-api-docs/pull/5186

feat(FormattingPatterns): add `ApplicationCommand`

---

deno/rest/v10/guild.ts
deno/rest/v9/guild.ts
rest/v10/guild.ts
rest/v9/guild.ts

* Added `delete_message_seconds`
* Marked `delete_message_days` as deprecated
* https://github.com/discord/discord-api-docs/pull/5219

feat(RESTPutAPIGuildBanJSONBody): add `delete_message_seconds`

---

deno/rest/v10/guild.ts
deno/rest/v9/guild.ts
rest/v10/guild.ts
rest/v9/guild.ts

- https://github.com/discord/discord-api-docs/pull/5261

fix(RESTPatchAPIGuildVoiceStateCurrentMemberJSONBody): `channel_id` is optional

---

deno/payloads/common.ts
payloads/common.ts

Adds the structure of a rate limit JSON response
https://discord.com/developers/docs/topics/rate-limits#exceeding-a-rate-limit-rate-limit-response-structure

feat: add `RESTRateLimit`

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
deno/rest/v10/channel.ts
deno/rest/v10/guild.ts
deno/rest/v9/channel.ts
deno/rest/v9/guild.ts
payloads/v10/channel.ts
payloads/v9/channel.ts
rest/v10/channel.ts
rest/v10/guild.ts
rest/v9/channel.ts
rest/v9/guild.ts

- discord/discord-api-docs#5488

feat(APIGuildForumChannel): add `default_sort_order`

---

deno/payloads/v10/auditLog.ts
deno/payloads/v9/auditLog.ts
payloads/v10/auditLog.ts
payloads/v9/auditLog.ts

`auto_moderation_rule_trigger_type` in the `APIAuditLogOptions` is a stringified version of `AutoModerationRuleTriggerType`. The typings have been more accurately reflected for this.

refactor(APIAuditLogOptions): Use `AuditLogRuleTriggerType` for `auto_moderation_rule_trigger_type`

---

deno/rest/v10/mod.ts
deno/rest/v9/mod.ts
rest/v10/index.ts
rest/v9/index.ts

Makes automod routes types compatible with `REST` by returning `as const` and adds missing reexport for automod json payloads for v10.

fix: export v10 json payloads and correct automod route types

---

deno/payloads/v10/_interactions/_applicationCommands/chatInput.ts
deno/payloads/v10/_interactions/_applicationCommands/contextMenu.ts
deno/payloads/v10/_interactions/applicationCommands.ts
deno/payloads/v10/_interactions/base.ts
deno/payloads/v10/_interactions/messageComponents.ts
deno/payloads/v10/channel.ts
deno/payloads/v9/_interactions/_applicationCommands/chatInput.ts
deno/payloads/v9/_interactions/_applicationCommands/contextMenu.ts
deno/payloads/v9/_interactions/applicationCommands.ts
deno/payloads/v9/_interactions/base.ts
deno/payloads/v9/_interactions/messageComponents.ts
deno/payloads/v9/channel.ts
deno/utils/v10.ts
deno/utils/v9.ts
payloads/v10/_interactions/_applicationCommands/chatInput.ts
payloads/v10/_interactions/_applicationCommands/contextMenu.ts
payloads/v10/_interactions/applicationCommands.ts
payloads/v10/_interactions/base.ts
payloads/v10/_interactions/messageComponents.ts
payloads/v10/channel.ts
payloads/v9/_interactions/_applicationCommands/chatInput.ts
payloads/v9/_interactions/_applicationCommands/contextMenu.ts
payloads/v9/_interactions/applicationCommands.ts
payloads/v9/_interactions/base.ts
payloads/v9/_interactions/messageComponents.ts
payloads/v9/channel.ts
tests/v10/interactions.test-d.ts
utils/v10.ts
utils/v9.ts

new selects! poggers thanks Ian
* https://github.com/discord/discord-api-docs/pull/5543
* https://github.com/discord/discord-api-docs/pull/5544

feat(Components): new select menus

---

deno/rest/v10/guild.ts
deno/rest/v10/interactions.ts
deno/rest/v9/guild.ts
deno/rest/v9/interactions.ts
rest/v10/guild.ts
rest/v10/interactions.ts
rest/v9/guild.ts
rest/v9/interactions.ts

Adds the following:
- `RESTGetAPIApplicationCommandsQuery`: query string of `GET /applications/{application.id}/commands`
- `RESTGetAPIApplicationGuildCommandsQuery`: query string of `GET /applications/{application.id}/guilds/{guild.id}/commands`
- `RESTPatchAPIGuildVoiceStateUserResult`: return type of `PATCH /guilds/{guild.id}/voice-states/{user.id}`

feat: add some missing REST types

---

deno/payloads/v10/guild.ts
deno/payloads/v9/guild.ts
payloads/v10/guild.ts
payloads/v9/guild.ts

This PR adds the item `DeveloperSupportServer` to the `GuildFeature` enum.
- https://github.com/discord/discord-api-docs/pull/5572

feat(GuildFeature): add `DeveloperSupportServer`

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
deno/rest/v10/channel.ts
deno/rest/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts
rest/v10/channel.ts
rest/v9/channel.ts

* https://github.com/discord/discord-api-docs/pull/5514

fix: `default_thread_rate_limit_per_user` is only for forum channels

---

deno/rest/v10/user.ts
deno/rest/v9/user.ts
rest/v10/user.ts
rest/v9/user.ts

Updates the limit for returned users' guilds to 200.
- https://github.com/discord/discord-api-docs/pull/2915

refactor(RESTGetAPICurrentUserGuildsQuery): Update guild limit

---

deno/rest/v10/voice.ts
deno/rest/v9/voice.ts
rest/v10/voice.ts
rest/v9/voice.ts

Thanks @IanMitchell for the report

fix: export `RESTGetAPIVoiceRegionsResult` with the correct name

---

deno/payloads/v10/user.ts
deno/payloads/v9/user.ts
payloads/v10/user.ts
payloads/v9/user.ts

The tsc is not able to compute the value of `Math.pow(2, 44)` at compile-time, leaving the `Quarantined` enum member without an initializer in the .d.ts file, which prevents thing such as:

fix(UserFlags): hardcode the value of `Quarantined`

---

deno/payloads/v10/autoModeration.ts
deno/payloads/v9/autoModeration.ts
payloads/v10/autoModeration.ts
payloads/v9/autoModeration.ts

This PR adds support for regex matching in auto moderation.
- https://github.com/discord/discord-api-docs/pull/5504

feat(APIAutoMod): add support for regex matching

---

deno/payloads/v10/channel.ts
deno/payloads/v8/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v8/channel.ts
payloads/v9/channel.ts

To my understanding, the position on a guild channel should never be missing or undefined, therefore it should not be marked as such. This PR marks the property as always present.

fix(APIGuildChannel): make position of guild channel non optional

---

deno/rest/v10/channel.ts
deno/rest/v9/channel.ts
rest/v10/channel.ts
rest/v9/channel.ts

Resolves #526:
- [`GET /channels/{channel.id}/threads/archived/public`](https://discord.com/developers/docs/resources/channel#list-public-archived-threads) is `RESTGetAPIChannelThreadsArchivedPublicResult`
- [`GET /channels/{channel.id}/threads/archived/private`](https://discord.com/developers/docs/resources/channel#list-private-archived-threads) is `RESTGetAPIChannelThreadsArchivedPrivateResult`
- [`GET /channels/{channel.id}/users/@me/threads/archived/private`](https://discord.com/developers/docs/resources/channel#list-joined-private-archived-threads) is `RESTGetAPIChannelUsersThreadsArchivedResult` (already exists)

fix(channel): Add missing thread-related results

---

deno/payloads/v10/channel.ts
deno/payloads/v10/guild.ts
deno/payloads/v9/channel.ts
deno/payloads/v9/guild.ts
payloads/v10/channel.ts
payloads/v10/guild.ts
payloads/v9/channel.ts
payloads/v9/guild.ts

This PR removes locales in links to help center articles (see [this comment](https://github.com/discordjs/discord-api-types/pull/653#discussion_r1031000020)) to prevent overriding a user's current locale. It additionally removes the title portion of urls (if present), leaving the ID.

docs: Remove locales and titles in help center article links

---

deno/payloads/v10/sticker.ts
deno/payloads/v9/sticker.ts
payloads/v10/sticker.ts
payloads/v9/sticker.ts

This PR changes the description of the `Guild` `StickerType` to reflect the change that all guilds now have access to uploading stickers, not just boosted servers.
[See related documentation PR](https://github.com/discord/discord-api-docs/pull/5048)

docs: update description for StickerType.Guild

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts
tests/v10/channel.test-d.ts

Types incorrectly assume PartialChannel objects will always have a name.
In some circumstances, PartialChannels may be DM channels, which do have a null name.
Also fixes the comment about minimum name length.
This change aligns with the already documented [Channel data structure](https://discord.com/developers/docs/resources/channel#channel-object-channel-structure)

fix(APIChannel): correctly type `name` based on channel type

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts
tests/v10/channel.test-d.ts

Sort-of follow up of #666 after finding out some additional problems with the typings of the `APIChannel`-related objects
- `default_thread_rate_limit_per_user` can be set on regular channels, despite the Discord client not showing this possibility, and newly created threads do abide by this configuration.
- `last_pin_timestamp` was not present on DM channels, despite them having this property.
Tests included
N/A

fix(APIChannel): correctly type present properties based on channel type

---

deno/payloads/v10/_interactions/applicationCommands.ts
deno/payloads/v10/_interactions/messageComponents.ts
deno/payloads/v9/_interactions/applicationCommands.ts
deno/payloads/v9/_interactions/messageComponents.ts
payloads/v10/_interactions/applicationCommands.ts
payloads/v10/_interactions/messageComponents.ts
payloads/v9/_interactions/applicationCommands.ts
payloads/v9/_interactions/messageComponents.ts

This makes `app_permissions` required in application command and message component interactions, where `channel_id` and `data` are set to required.
Currently discord-api-types is very inconsistent about interaction required fields and more work should probably be done to fix that; this might be due to the docs also being inconsistent about these
locale is set as required in the interaction structure but then removed in ping
data is set as optional in the interaction structure but then set as required in all subinterfaces except ping
channel_id is set as optional in the interaction structure but then set as required for cmds and components, although it should also be required in autocomplete and modal submit
for now I just made autocomplete copy channel_id's current behavior as a quick …

fix(Interactions): make app_permissions required

---

deno/payloads/v10/user.ts
deno/payloads/v9/user.ts
deno/rest/v10/user.ts
deno/rest/v9/user.ts
payloads/v10/user.ts
payloads/v9/user.ts
rest/v10/user.ts
rest/v9/user.ts

The metadata keys can be strings or integers, as can be seen in the official example
https://github.com/discord/linked-roles-sample/blob/013fb8f30ecb484324a53093f912a08122a03167/src/server.js#L113-L117
It does not support boolean values as per https://github.com/discord/discord-api-docs/issues/5755#issuecomment-1353749675

fix(APIApplicationRoleConnection): `metadata` values can be numbers

---

deno/rest/v10/auditLog.ts
deno/rest/v9/auditLog.ts
rest/v10/auditLog.ts
rest/v9/auditLog.ts

Supports the `after` query parameter in guild audit log fetching.
- https://github.com/discord/discord-api-docs/pull/5821

feat(RESTGetAPIAuditLogQuery): Support `after`

---

deno/payloads/common.ts
deno/rest/common.ts
payloads/common.ts
rest/common.ts

```json
{
"code": 40062,
"global": false,
"message": "Service resource is being rate limited.",
"retry_after": 3
}
```
* https://github.com/discord/discord-api-docs/pull/5574

feat: add RESTJSONErrorCode `40062` and RESTRateLimit.code

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

- Adds support for a field that is guaranteed to appear in the relevant payload
- https://github.com/discord/discord-api-docs/pull/5867

feat: add `managed` field to `ChannelType.GroupDM`

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

Removes the `@unstable` tag from these stage-related message types.
- https://github.com/discord/discord-api-docs/pull/5927

refactor(MessageType): remove `@unstable` stage message types

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

For text in voice, #544, was adding **APIVoiceChannelBase**. With text and video in stages, both channel types now have text-based and video properties. So, **APIVoiceChannelBase** needs to be complemented with all of these properties.

refactor(APIVoiceChannelBase): support text and video in stages

---

deno/payloads/v10/autoModeration.ts
deno/payloads/v9/autoModeration.ts
payloads/v10/autoModeration.ts
payloads/v9/autoModeration.ts

- https://github.com/discord/discord-api-docs/pull/5955

feat(AutoModeration): add `custom_message` field support

---

deno/rest/v10/channel.ts
deno/rest/v9/channel.ts
rest/v10/channel.ts
rest/v9/channel.ts

`RESTPostAPIChannelMessagesThreadsJSONBody` marks `auto_archive_duration` as required, however, the [documentation](https://discord.com/developers/docs/resources/channel#start-thread-from-message) indicates it's optional.
https://discord.com/developers/docs/resources/channel#start-thread-from-message

fix(RESTPostAPIChannelMessagesThreadsJSONBody): mark `auto_archive_duration` as optional

---

deno/gateway/v10.ts
deno/gateway/v9.ts
gateway/v10.ts
gateway/v9.ts

When requesting guild members over the gateway (v9 & v10) and receiving guild member chunks, the presence data does not include the guild id.

fix(GatewayGuildMembersChunkDispatchData): Omit `guild_id` for presences

---

package.json

I moved `types` condition to the front. `package.json#exports` are **order-sensitive** - they are always matched from the top to the bottom. When a match is found then it should be used and no further matching should occur. 
Right now, the current setup works in TypeScript but it's considered a bug and it should not be relied upon, see the thread and the comment [here](https://github.com/microsoft/TypeScript/issues/50762#issuecomment-1528318260). For that reason, I would like to fix all popular packages that misconfigured their `exports` this way so the bug can be fixed in TypeScript.
⚠️ this PR focuses solely on fixing "🐛 Used fallback condition" problem but the "🎭 Masquerading as CJS" remains here. You can check the reported errors …

Fix: move `types` condition to the front

---

deno/payloads/v10/_interactions/_applicationCommands/_chatInput/base.ts
deno/payloads/v9/_interactions/_applicationCommands/_chatInput/base.ts
payloads/v10/_interactions/_applicationCommands/_chatInput/base.ts
payloads/v9/_interactions/_applicationCommands/_chatInput/base.ts

https://github.com/discordjs/discord.js/blob/6229597db2be67be9e3aa0bf05574d826315eb36/packages/builders/__tests__/interactions/SlashCommands/Options.test.ts#L103-L106

fix: allow sending empty choices with autocomplete: true

---

deno/payloads/common.ts
payloads/common.ts

- discord/discord-api-docs#6039

chore(PermissionFlagsBits): mark `UseExternalSounds` as stable

---

deno/payloads/v10/channel.ts
deno/payloads/v8/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v8/channel.ts
payloads/v9/channel.ts

[APITextInputComponent](https://discord-api-types.dev/api/discord-api-types-v8/interface/APITextInputComponent#label) shows max 80 characters but it's actually 45 characters according to [Text Input Structure](https://discord.com/developers/docs/interactions/message-components#text-inputs-text-input-structure)

docs(APITextInputComponent): correct label max characters

---

deno/payloads/v10/gateway.ts
deno/payloads/v10/guild.ts
deno/payloads/v9/gateway.ts
deno/payloads/v9/guild.ts
payloads/v10/gateway.ts
payloads/v10/guild.ts
payloads/v9/gateway.ts
payloads/v9/guild.ts

it says
> Either "idle", "dnd", "online", or "offline"
but the types say it can also be "invisible". this fixes that by adding a new `PresenceUpdateReceiveStatus` type which is `PresenceUpdateStatus` without "invisible", and updates receive interfaces to use the new type

fix(Presence): cannot receive invisible status

---

deno/rest/v10/channel.ts
deno/rest/v9/channel.ts
rest/v10/channel.ts
rest/v9/channel.ts

The `id` is currently required when updating a tag for a forum channel which cannot be obtained for tags that do not exist. Per the documentation, only the `name` is required.
- https://github.com/discord/discord-api-docs/pull/5458

fix(RESTPatchAPIChannelJSONBody): `available_tags` requires `name` only

---

deno/payloads/v10/permissions.ts
deno/payloads/v9/permissions.ts
payloads/v10/permissions.ts
payloads/v9/permissions.ts

Just adds discord docs url to enum descirption

chore(RoleFlags): add link to api docs

---

deno/rest/v10/guild.ts
deno/rest/v8/guild.ts
deno/rest/v9/guild.ts
rest/v10/guild.ts
rest/v8/guild.ts
rest/v9/guild.ts

The usage of 'never' in discord-api-types for all API responses with a 204 (empty) response leads to potential confusion among developers due to implicit precedence given to the declared type in TypeScript. It is essential to diligently avoid such undesirable situations.

fix(Guild): union with never type

---

deno/rest/v10/channel.ts
deno/rest/v10/webhook.ts
deno/rest/v9/channel.ts
deno/rest/v9/webhook.ts
rest/v10/channel.ts
rest/v10/webhook.ts
rest/v9/channel.ts
rest/v9/webhook.ts

`id`s in the `attachments` array should also be typed as `number`s to match `files[n]`, if necessary.
https://discord.com/developers/docs/reference#uploading-files

fix(RESTPostAPIChannelMessageJSONBody): `number` for attachment ids

---

deno/payloads/v10/sticker.ts
deno/payloads/v9/sticker.ts
deno/rest/v10/mod.ts
deno/rest/v10/sticker.ts
deno/rest/v9/mod.ts
deno/rest/v9/sticker.ts
payloads/v10/sticker.ts
payloads/v9/sticker.ts
rest/v10/index.ts
rest/v10/sticker.ts
rest/v9/index.ts
rest/v9/sticker.ts

- https://github.com/discord/discord-api-docs/pull/6265

fix: standard stickers are now free

---

deno/payloads/v10/_interactions/base.ts
deno/payloads/v10/channel.ts
deno/payloads/v9/_interactions/base.ts
deno/payloads/v9/channel.ts
deno/rest/v10/channel.ts
deno/rest/v9/channel.ts
payloads/v10/_interactions/base.ts
payloads/v10/channel.ts
payloads/v9/_interactions/base.ts
payloads/v9/channel.ts
rest/v10/channel.ts
rest/v9/channel.ts

- Brings `APIInteractionDataResolvedChannel`  into line with the [API specification](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-resolved-data-structure) (`thread_metadata`, `parent_id` only exist on thread channel partials)
- adds the utility type `ThreadChannelType` to facilitate the above, which also allows some deduping in the type declaration for `APIThreadChannel`

refactor(APIInteractionDataResolvedChannel): thread channels

---

deno/payloads/common.ts
payloads/common.ts

- https://github.com/discord/discord-api-docs/pull/6305

feat(PermissionFlagsBits): split up expressions and events perms

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

These are not text channel-like. It is the threads within these channels that are.
Removing these from the union brought about an error on `APIGuildTextChannel` as `APIThreadOnlyChannel` extended this. It contains the same properties needed for thread-based channels _and_ text channels, so I just added the forum and media channel types there. Maybe in the future, the class could be renamed.

fix(TextChannelType): Remove forum and media channels

---

.vscode/settings.json

Boolean values will soon be deprecated, and these values are automatically changed whenever you launch Visual Studio Code (only Insiders for now as far as I know).

chore: use string values in vs code settings

---

deno/rest/v10/mod.ts
deno/rest/v9/mod.ts
rest/v10/index.ts
rest/v9/index.ts

Fixes the issue addressed in #866, `storePageAsset` only returns the PNG route but the Discord documentation says that route supports PNG, JPEG, and WebP.

fix(CDNRoutes): fix store page wrong extension

---

deno/rest/v10/mod.ts
deno/rest/v9/mod.ts
rest/v10/index.ts
rest/v9/index.ts

Didn't realize #867 would be a breaking change, oops! This makes format parameter optional and defaults to PNG to make sure nothing breaks.

fix(CDNRoutes): make format optional and default to png

---

deno/rest/v10/mod.ts
deno/rest/v9/mod.ts
rest/v10/index.ts
rest/v9/index.ts

Implements generics for `format` options. This removes the cumbersome template literal union typings that are returned, and allows those using CDNRoutes to more easily understand what's returned from a given route function. Retains strict boundaries for what extensions are allowed to be used for a given route.
close #866

types(CDNRoutes): use generics for `format` options

---

deno/rest/v10/channel.ts
deno/rest/v9/channel.ts
rest/v10/channel.ts
rest/v9/channel.ts

- https://github.com/discord/discord-api-docs/pull/6647

feat(RESTPostAPIChannelMessageJSONBody): add enforce_nonce

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

https://discord.com/developers/docs/interactions/message-components#select-menu-object-select-option-structure

docs(APISelectMenuOption): correct character limit

---

.github/workflows/create-pr-for-release-and-publish.yml
.github/workflows/publish-next.yml
package.json

Basically discordjs/discord.js#10164 for discord-api-types
I didn't use the `--provenance` flag for the workflow this time as this repo contains only a single package (it's hard not to include provenance in `package.json` if there's only a single package to maintain). As long as the `package.json` file has it it should be good

ci: enable npm provenance

---

deno/payloads/v10/auditLog.ts
deno/payloads/v9/auditLog.ts
payloads/v10/auditLog.ts
payloads/v9/auditLog.ts

Adds missing `system_channel_flags` AuditLogChangeKey.

feat(APIAuditLogChange): add `APIAuditLogChangeKeySystemChannelFlags`

---

deno/payloads/v10/stageInstance.ts
payloads/v10/stageInstance.ts

The public `StageInstancePrivacyLevel` is marked as deprecated because the first pull request #317 missed this in v10.

chore(StageInstancePrivacyLevel): mark public PrivacyLevel as deprecated

---

deno/payloads/v10/poll.ts
deno/payloads/v9/poll.ts
payloads/v10/poll.ts
payloads/v9/poll.ts

Fixing a error in the poll answer properties according to the discord docs
https://canary.discord.com/developers/docs/resources/poll#poll-answer-object-poll-answer-object-structure

fix(Polls): correct APIPollAnswer properties

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

- https://github.com/discord/discord-api-docs/pull/6864

feat(APIMessage): add `call`

---

deno/payloads/v10/auditLog.ts
deno/payloads/v9/auditLog.ts
payloads/v10/auditLog.ts
payloads/v9/auditLog.ts

> `new_value` is an array of objects that contain the role `id` and `name`
https://canary.discord.com/developers/docs/resources/audit-log#audit-log-change-object-audit-log-change-exceptions:~:text=as%20keys-,new_value,name,-Webhook

fix: Correct types for `APIAuditLogChangeKey$Add` and `APIAuditLogChangeKey$Remove`

---

deno/rest/v10/mod.ts
rest/v10/index.ts

Adds the media proxy URL as GIF stickers are accessed there.
https://discord.com/developers/docs/reference#image-formatting-cdn-endpoints

feat(RouteBases): Add media URL

---

deno/payloads/v10/_interactions/responses.ts
deno/payloads/v10/channel.ts
deno/payloads/v9/_interactions/responses.ts
deno/payloads/v9/channel.ts
payloads/v10/_interactions/responses.ts
payloads/v10/channel.ts
payloads/v9/_interactions/responses.ts
payloads/v9/channel.ts

Adds support for premium button types and deprecates premium interaction response types.
https://github.com/discord/discord-api-docs/pull/6875

feat: add premium buttons

---

.eslintignore
.prettierignore
scripts/deno.mjs

The files for deprecated versions were still being linted and causing warnings in CI. Ignore them as they won't be updated anymore

chore: ignore deprecated versions on linters

---

deno/rest/v10/emoji.ts
deno/rest/v10/mod.ts
deno/rest/v9/emoji.ts
deno/rest/v9/mod.ts
rest/v10/emoji.ts
rest/v10/index.ts
rest/v9/emoji.ts
rest/v9/index.ts

- https://github.com/discord/discord-api-docs/pull/7010

feat: application emojis

---

deno/rest/v10/mod.ts
deno/rest/v9/mod.ts
rest/v10/index.ts
rest/v9/index.ts

**Please describe the changes this PR makes and why it should be merged:** It fixes an inconsistency in the guildIcon cdn route. This route does not start with `/` like the rest of the routes. It also fixes it's JSDoc which is completely wrong.
**If applicable, please reference Discord API Docs PRs or commits that influenced this PR:** None

fix(CDNRoutes): inconsistency in route and wrong JSDoc

---

deno/rest/v10/guild.ts
deno/rest/v10/mod.ts
deno/rest/v9/guild.ts
deno/rest/v9/mod.ts
rest/v10/guild.ts
rest/v10/index.ts
rest/v9/guild.ts
rest/v9/index.ts

Updates JSDoc and adds type for using GET method on an individual role.
- https://github.com/discord/discord-api-docs/pull/7074

feat(Routes): get method on role endpoint

---

deno/rest/v10/oauth2.ts
deno/rest/v9/oauth2.ts
rest/v10/oauth2.ts
rest/v9/oauth2.ts

The `RESTPostOAuth2TokenRevocationQuery` provides expected types for the [`Token Revocation URL`](https://discord.com/developers/docs/topics/oauth2)
Please let me know if you have any further requests or modifications!

feat(RESTOAuth2): add RESTPostOAuth2TokenRevocationQuery

---

deno/rest/v10/guildScheduledEvent.ts
deno/rest/v9/guildScheduledEvent.ts
rest/v10/guildScheduledEvent.ts
rest/v9/guildScheduledEvent.ts

fix: nullable fields for scheduled event editing

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
deno/rest/v10/channel.ts
deno/rest/v10/webhook.ts
deno/rest/v9/channel.ts
deno/rest/v9/webhook.ts
payloads/v10/channel.ts
payloads/v9/channel.ts
rest/v10/channel.ts
rest/v10/webhook.ts
rest/v9/channel.ts
rest/v9/webhook.ts

The documentation isn't clear about what fields can be sent when creating messages, so I checked the spec and added the missing fields
- <https://discord.com/developers/docs/resources/message#create-message-jsonform-params>
https://github.com/discord/discord-api-spec/blob/f31843808734a58e4c351fba6fd5768bb480b066/specs/openapi.json#L22778-L22831
Ignored `is_remix` since that field isn't documented at all

feat(RESTAPIAttachment): add more properties

---

deno/payloads/v10/application.ts
deno/payloads/v10/sticker.ts
deno/payloads/v9/application.ts
deno/payloads/v9/sticker.ts
payloads/v10/application.ts
payloads/v10/sticker.ts
payloads/v9/application.ts
payloads/v9/sticker.ts

- https://github.com/discord/discord-api-docs/pull/7114

docs: mark `APIApplication#summary` and `APISticker#asset` as unstable

---

deno/globals.ts
globals.ts

Added missing formatting patterns for guild navigation and linked roles

feat(FormattingPatterns): `GuildNavigation` and `LinkedRole`

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

This field was in the initial commits of Discord API Docs PR but was later removed before the PR being merged
- https://github.com/discord/discord-api-docs/pull/6833
- https://github.com/discordjs/discord-api-types/pull/971

fix(APIMessageSnapshot): mark `guild_id` as deprecated

---

deno/rest/v10/webhook.ts
deno/rest/v9/webhook.ts
rest/v10/webhook.ts
rest/v9/webhook.ts

Replaces the deprecated `RESTAPIPollCreate` with `RESTAPIPoll` after #1065. Stops the CI tests from failing

fix: replace deprecated `RESTAPIPollCreate` with `RESTAPIPoll`

---

deno/payloads/v10/auditLog.ts
deno/payloads/v9/auditLog.ts
payloads/v10/auditLog.ts
payloads/v9/auditLog.ts

Includes the `premium_progress_bar_enabled` key for the Audit Log Change object
_None_
Completes #1119

feat: audit log change key for boost bar

---

deno/utils/v10.ts
deno/utils/v9.ts
utils/v10.ts
utils/v9.ts

It was addressed internally [here](https://canary.discord.com/channels/222078108977594368/1209960895141388389/1303096590772211884). Fixes `isInteractionButton` to check for `ButtonStyle.Premium`
- https://github.com/discord/discord-api-docs/pull/6875

fix(isInteractionButton): handle `ButtonStyle.Premium`

---

deno/gateway/v10.ts
deno/gateway/v9.ts
gateway/v10.ts
gateway/v9.ts

Message updates now contain full message object.
- https://github.com/discord/discord-api-docs/pull/7017

feat(GatewayMessageUpdateDispatchData): Use full message object

---

deno/payloads/common.ts
deno/payloads/v10/_interactions/base.ts
deno/payloads/v10/guild.ts
deno/payloads/v10/template.ts
deno/payloads/v9/_interactions/base.ts
deno/payloads/v9/guild.ts
deno/payloads/v9/template.ts
deno/rest/common.ts
deno/rest/v10/guild.ts
deno/rest/v9/guild.ts
payloads/common.ts
payloads/v10/_interactions/base.ts
payloads/v10/guild.ts
payloads/v10/template.ts
payloads/v9/_interactions/base.ts
payloads/v9/guild.ts
payloads/v9/template.ts
rest/common.ts
rest/v10/guild.ts
rest/v9/guild.ts

Deprecates `LocaleString` (to use `Locale` instead).

refactor: Deprecate `LocaleString`

---

deno/rest/v10/channel.ts
deno/rest/v9/channel.ts
rest/v10/channel.ts
rest/v9/channel.ts

Made this more generic as this is not for only replying any more (since #971).

docs(RESTPostAPIChannelMessageJSONBody): Make message reference generic

---

deno/payloads/v10/_interactions/base.ts
deno/payloads/v10/guild.ts
deno/payloads/v9/_interactions/base.ts
deno/payloads/v9/guild.ts
payloads/v10/_interactions/base.ts
payloads/v10/guild.ts
payloads/v9/_interactions/base.ts
payloads/v9/guild.ts

Resolves #1133.
The partial guild object returns `locale` instead of `preferred_locale`. There is an open issue about this: https://github.com/discord/discord-api-docs/issues/6938. I wasn't sure whether to mark this as `@unstable`, so I've left it as a `@remark`.
Upstream:
- https://github.com/discord/discord-api-docs/pull/6870

feat(_interactions): Support partial guild objects

---

deno/gateway/v10.ts
deno/gateway/v9.ts
gateway/v10.ts
gateway/v9.ts

- `channels` will not contain direct message channels or group direct message channels. These are channels attached to a guild.
- `threads` are, well, threads. This cannot contain category channels, for example.
N/A

refactor(GatewayGuildCreateDispatchData): Narrow `channels` and `threads` types

---

deno/gateway/v10.ts
deno/gateway/v9.ts
gateway/v10.ts
gateway/v9.ts

Narrowed the `CHANNEL_CREATE`, `CHANNEL_DELETE`, and `CHANNEL_UPDATE` gateway events types.
It is [documented](https://discord.com/developers/docs/events/gateway-events#channel-create) that channel creations are guild channels. This excludes threads, which have their own gateway events. Does not seem like direct message channels trigger update or delete either.
Made `guild_id` present. [It's only missing on guild dispatches](https://discord.com/developers/docs/resources/channel#channel-object-channel-structure).
I had to touch the deprecated `GatewayThreadModifyDispatch` type as the payload would have been wrong.

refactor: Narrow channel gateway events types

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

- https://github.com/discord/discord-api-docs/pull/3404

refactor(APIThreadMetadata): `locked` is always present

---

deno/payloads/v10/gateway.ts
deno/payloads/v9/gateway.ts
payloads/v10/gateway.ts
payloads/v9/gateway.ts

Narrowed the `threads` property to only contain threads.

refactor(GatewayThreadListSync): Narrow `threads`

---

deno/payloads/v10/monetization.ts
deno/payloads/v9/monetization.ts
payloads/v10/monetization.ts
payloads/v9/monetization.ts

- https://github.com/discord/discord-api-docs/pull/7288

refactor(APIEntitlement): update `ends_at` and `starts_at` to be nullable

---

.github/ISSUE_TEMPLATE/feature_request.yml

The "discussion" label does not exist. Using an existing one.

chore: Use feature request label for feature requests

---

deno/payloads/v10/channel.ts
deno/payloads/v6/channel.ts
deno/payloads/v8/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v6/channel.ts
payloads/v8/channel.ts
payloads/v9/channel.ts

close #1186
Discord API documentation removed the deprecation message for EmbedType at [discord/discord-api-docs#7050](https://github.com/discord/discord-api-docs/pull/7050). This PR undeprecates the associated property and enum.

fix(MessageEmbed): remove deprecation for EmbedType

---

deno/payloads/v10/_interactions/responses.ts
deno/payloads/v9/_interactions/responses.ts
payloads/v10/_interactions/responses.ts
payloads/v9/_interactions/responses.ts

Removes the override of `flags`. This was harmful with `exactOptionalPropertyTypes` enabled.

refactor(APIInteractionResponseCallbackData): Remove `flags` override

---

deno/payloads/v10/_interactions/_applicationCommands/_chatInput/integer.ts
deno/payloads/v10/_interactions/_applicationCommands/_chatInput/number.ts
deno/payloads/v10/_interactions/_applicationCommands/_chatInput/subcommand.ts
deno/payloads/v10/_interactions/_applicationCommands/_chatInput/subcommandGroup.ts
deno/payloads/v10/_interactions/_applicationCommands/chatInput.ts
deno/payloads/v10/_interactions/autocomplete.ts
deno/payloads/v9/_interactions/_applicationCommands/_chatInput/integer.ts
deno/payloads/v9/_interactions/_applicationCommands/_chatInput/number.ts
deno/payloads/v9/_interactions/_applicationCommands/_chatInput/subcommand.ts
deno/payloads/v9/_interactions/_applicationCommands/_chatInput/subcommandGroup.ts
deno/payloads/v9/_interactions/_applicationCommands/chatInput.ts
deno/payloads/v9/_interactions/autocomplete.ts
payloads/v10/_interactions/_applicationCommands/_chatInput/integer.ts
payloads/v10/_interactions/_applicationCommands/_chatInput/number.ts
payloads/v10/_interactions/_applicationCommands/_chatInput/subcommand.ts
payloads/v10/_interactions/_applicationCommands/_chatInput/subcommandGroup.ts
payloads/v10/_interactions/_applicationCommands/chatInput.ts
payloads/v10/_interactions/autocomplete.ts
payloads/v9/_interactions/_applicationCommands/_chatInput/integer.ts
payloads/v9/_interactions/_applicationCommands/_chatInput/number.ts
payloads/v9/_interactions/_applicationCommands/_chatInput/subcommand.ts
payloads/v9/_interactions/_applicationCommands/_chatInput/subcommandGroup.ts
payloads/v9/_interactions/_applicationCommands/chatInput.ts
payloads/v9/_interactions/autocomplete.ts
tests/v10/interactions.ts

Resolves #1175.
A type argument of the interaction type is passed to the integer and number options to know whether to return a string if it came from an autocomplete interaction.

fix: Ensure autocomplete option values resolve to string for numerical types

---

deno/rest/v10/mod.ts
deno/rest/v9/mod.ts
rest/v10/index.ts
rest/v9/index.ts

Allow other sizes for `ImageSize`, as many others can also be used. Internal discussion [here](https://canary.discord.com/channels/222078108977594368/999796393810067607/1364005073432346797)

refactor(ImageSize): allow other sizes

---

deno/payloads/v10/application.ts
deno/payloads/v10/channel.ts
deno/payloads/v9/application.ts
deno/payloads/v9/channel.ts
payloads/v10/application.ts
payloads/v10/channel.ts
payloads/v9/application.ts
payloads/v9/channel.ts

https://support-dev.discord.com/hc/articles/4404772028055 is no longer available. https://support-dev.discord.com/hc/articles/6207308062871 seems to be a suitable replacement.

docs: Update privilege intents link

---

deno/payloads/v10/emoji.ts
deno/payloads/v9/emoji.ts
deno/rest/v10/emoji.ts
deno/rest/v9/emoji.ts
payloads/v10/emoji.ts
payloads/v9/emoji.ts
rest/v10/emoji.ts
rest/v9/emoji.ts

Application emojis' types are slightly different from `APIEmoji`. Made this more apparent.

feat: Specific typings for application emojis

---

deno/payloads/v10/_interactions/applicationCommands.ts
deno/payloads/v10/channel.ts
deno/payloads/v10/guild.ts
deno/payloads/v9/_interactions/applicationCommands.ts
deno/payloads/v9/channel.ts
deno/payloads/v9/guild.ts
deno/rest/v10/channel.ts
deno/rest/v10/guild.ts
deno/rest/v10/monetization.ts
deno/rest/v10/webhook.ts
deno/rest/v9/channel.ts
deno/rest/v9/guild.ts
deno/rest/v9/monetization.ts
deno/rest/v9/webhook.ts
deno/rpc/v10.ts
payloads/v10/_interactions/applicationCommands.ts
payloads/v10/channel.ts
payloads/v10/guild.ts
payloads/v9/_interactions/applicationCommands.ts
payloads/v9/channel.ts
payloads/v9/guild.ts
rest/v10/channel.ts
rest/v10/guild.ts
rest/v10/monetization.ts
rest/v10/webhook.ts
rest/v9/channel.ts
rest/v9/guild.ts
rest/v9/monetization.ts
rest/v9/webhook.ts
rpc/v10.ts

Removes duplication in descriptions and uses `@defaultValue` instead, pointed out [here](https://github.com/discordjs/discord-api-types/pull/1224#discussion_r2055780708), internal discussion [here](https://canary.discord.com/channels/222078108977594368/999796393810067607/1364556416228134943)

docs: remove duplication in descriptions

---

deno/payloads/v10/channel.ts
deno/payloads/v10/invite.ts
deno/payloads/v9/channel.ts
deno/payloads/v9/invite.ts
payloads/v10/channel.ts
payloads/v10/invite.ts
payloads/v9/channel.ts
payloads/v9/invite.ts

The channel of an `APIInvite` did not have all associated properties. Taken from the [specification](https://github.com/discord/discord-api-spec/blob/bed14af32d02a6feb2c0e1a778a7b1e8eebd1570/specs/openapi.json#L23018) (alongside testing), a more accurate interface has been created.

feat: `APIInviteChannel`

---

deno/payloads/v10/channel.ts
deno/payloads/v10/webhook.ts
deno/payloads/v9/channel.ts
deno/payloads/v9/webhook.ts
payloads/v10/channel.ts
payloads/v10/webhook.ts
payloads/v9/channel.ts
payloads/v9/webhook.ts

The source channel of a webhook was previously typed to include `type`. However, from testing, `type` is not received:
```JavaScript
{
application_id: null,
avatar: '8d2f3da86b058d315a43e541094f0b55',
channel_id: '1089219063567360130',
guild_id: '1089217648996401242',
id: '1370316514422423584',
name: '[need a ducking name] #important-innit',
type: 2,
user: {...},
source_guild: {
id: '1089217648996401242',
icon: '8d2f3da86b058d315a43e541094f0b55',
name: '[need a ducking name]'
},
source_channel: { id: '1370316432482631720', name: 'important-innit' }
}
```
[The specification](https://github.com/discord/discord-api-spec/blob/18275bc9b9d4c354136b43c531a97057c8789ff4/specs/openapi.json#L33084-L33098) also states it is not present.

feat: `APIWebhookSourceChannel`

---

deno/payloads/v10/guild.ts
deno/payloads/v10/webhook.ts
deno/payloads/v9/guild.ts
deno/payloads/v9/webhook.ts
payloads/v10/guild.ts
payloads/v10/webhook.ts
payloads/v9/guild.ts
payloads/v9/webhook.ts

Noticed from #1235, the source guild is typed to contain many properties it does not have. [The specification](https://github.com/discord/discord-api-spec/blob/18275bc9b9d4c354136b43c531a97057c8789ff4/specs/openapi.json#L33099-L33119) only lists 3.

feat: `APIWebhookSourceGuild`

---

.eslintrc.json
deno/rest/v10/oauth2.ts
deno/rest/v9/oauth2.ts
rest/v10/oauth2.ts
rest/v9/oauth2.ts
tests/v10/oauth2.ts
tests/v9/oauth2.ts

<https://discord.com/developers/docs/topics/oauth2#authorization-code-grant>
All the examples in the documentation use HTTP basic authentication instead of the `client_id` and `client_secret` fields approach

fix: optional `client_id` and `client_secret` in access token data

---

deno/payloads/v10/webhook.ts
deno/payloads/v9/webhook.ts
payloads/v10/webhook.ts
payloads/v9/webhook.ts

The developer portal exposes more options that do not appear to be documented. This one will add `APPLICATION_DEAUTHORIZED` with the unstable tag.
Example payload:
```JSON
{
"data": {
"user": {
"avatar": "1f341400799da66e593f58e2e4bdf066",
"clan": {
"identity_enabled": false
},
"discriminator": "0",
"global_name": "Jiralite",
"id": "<id>",
"primary_guild": {
"identity_enabled": false
},
"public_flags": 4210944,
"username": "jiralite"
}
},
"timestamp": "2025-05-28T18:14:24.852266",
"type": "APPLICATION_DEAUTHORIZED"
}
```

feat: Add application deauthorised webhook event

---

deno/voice/v8.ts
voice/v8.ts

Added `max_dave_protocol_version` to the voice identify payload, missed this from the whitepaper.

fix(voice): add `max_dave_protocol_version` to identify

---

deno/voice/v4.ts
deno/voice/v8.ts
voice/v4.ts
voice/v8.ts

Added close codes 4021 (Disconnected: Rate Limited) and 4022 (Disconnected: Call Terminated)
https://github.com/discord/discord-api-docs/commit/ea32903a5219be24708ba02b1b9ea1bc6444432d
https://github.com/discord/discord-api-docs/pull/7582

feat(voice): add close codes 4021 and 4022

---

deno/rest/v10/mod.ts
deno/rest/v9/mod.ts
rest/v10/index.ts
rest/v9/index.ts

Missed this change made just before the upstream PR was merged
- https://github.com/discord/discord-api-docs/pull/6836

fix(CDNRoutes): correct `guildTagBadge` route

---

deno/payloads/v10/_interactions/_applicationCommands/_chatInput/channel.ts
deno/payloads/v9/_interactions/_applicationCommands/_chatInput/channel.ts
payloads/v10/_interactions/_applicationCommands/_chatInput/channel.ts
payloads/v9/_interactions/_applicationCommands/_chatInput/channel.ts

In a hub, there are no channels to type in – only a directory channel. Commands cannot be used (applications are not populated), so there is no chance of getting a directory channel.

fix(APIApplicationCommandChannelOption): Exclude directory channels

---

deno/payloads/v10/_interactions/modalSubmit.ts
deno/payloads/v9/_interactions/modalSubmit.ts
payloads/v10/_interactions/modalSubmit.ts
payloads/v9/_interactions/modalSubmit.ts

Apparently text display is also returned in components in modal submissions.
ref: https://canary.discord.com/channels/1317206872763404478/1317208024682725426/1413548755470389338

fix: add missing text display in modal submission

---

deno/gateway/v10.ts
deno/gateway/v9.ts
gateway/v10.ts
gateway/v9.ts

- https://github.com/discord/discord-api-docs/pull/7760

feat: add RateLimited gateway event

---

deno/gateway/v10.ts
deno/gateway/v9.ts
deno/payloads/v10/voice.ts
deno/payloads/v9/voice.ts
gateway/v10.ts
gateway/v9.ts
payloads/v10/voice.ts
payloads/v9/voice.ts

#1290 accidentally stripped the `guild_id` from `GatewayVoiceStateUpdateDispatchData`. After re-adding this back, I noticed it loops back around to being 1:1 with `APIVoiceState` making the whole change to `GatewayVoiceStateUpdateDispatchData` unnecessary in the first place.
As for how `GatewayVoiceStateUpdateDispatchData` was used in `GatewayGuildCreateDispatchData`, I noticed the aforementioned PR already looped back around to `APIVoiceStateMember#member` being the same as it was originally as `APIBaseVoiceState#member`. So, the changes to `GatewayGuildCreateDispatchData` and `APIBaseVoiceState` were also unnecessary.
Therefore, this partially reverts #1290.
**If applicable, please reference Discord API Docs PRs …

fix: add guild_id back to GatewayVoiceStateUpdateDispatchData

---

deno/payloads/v10/channel.ts
deno/payloads/v9/channel.ts
payloads/v10/channel.ts
payloads/v9/channel.ts

Narrows the property **`parent_id`** for:
- **`APIThreadChannel`**: now includes` parent_id?: Snowflake`,  reflecting its parent thread relationship.
- **`APIGuildCategoryChannel`**: now includes `parent_id?: null`, clarifying that categories do not have a parent.
Narrows the property **`applied_tags`** for:
- **`APIThreadOnlyChannel`**: now **`applied_tags: Snowflake[]`** is explicit to this type.
Reference: https://discord.com/developers/docs/resources/channel#channel-object-channel-structure

fix: Narrow thread-related properties for channels

---

deno/payloads/v10/guild.ts
deno/payloads/v9/guild.ts
deno/rest/v10/guild.ts
deno/rest/v10/mod.ts
deno/rest/v9/guild.ts
deno/rest/v9/mod.ts
payloads/v10/guild.ts
payloads/v9/guild.ts
rest/v10/guild.ts
rest/v10/index.ts
rest/v9/guild.ts
rest/v9/index.ts

Some documentation was removed in https://github.com/discord/discord-api-docs/pull/2547, so existing types are now `@unstable`.

fix: `@unstable` membership screening
